Repository easyops-cn/next-core, pull requests merged in 2021-12, with the labels that each got.

#1216 fix(): 移除之前使用 legcay bootstrap 接口的开关
  packages/brick-container/serve/serveLocal.js
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
Labels: eve: release after merged

#1220 chore(EasyopsEmpty): 统一修改无数据的svg图MONITOR-2520 Refs
  packages/brick-kit/src/EasyopsEmpty/EasyopsEmpty.tsx
  packages/brick-kit/src/EasyopsEmpty/empty-image.svg
Labels: eve: release after merged

#1221 fix(): fix page tracker
  packages/brick-kit/src/core/Router.ts
Labels: eve: release after merged

#1222 fix(): add icons field
  packages/brick-kit/src/core/Kernel.ts
Labels: eve: release after merged

#1231 fix(): fix empty image
  packages/brick-container/webpack/common.js
  packages/brick-kit/rollup.config.js
  packages/brick-kit/src/EasyopsEmpty/EasyopsEmpty.spec.tsx
  packages/brick-kit/src/EasyopsEmpty/EasyopsEmpty.tsx
  packages/brick-kit/src/EasyopsEmpty/empty-grey-image.svg
  packages/brick-kit/src/EasyopsEmpty/empty-light-grey-image.svg
  packages/brick-kit/src/images/empty-image.png
Labels: eve: release after merged

#1243 chore(): add new icons
  packages/brick-icons/src/icons/database.svg
  packages/brick-icons/src/icons/devops.svg
  packages/brick-icons/src/icons/monitor.svg
Labels: eve: release after merged

#1251 fix(): refine generating contracts for bricks
  packages/webpack-config-factory/src/bricks/webpack.contracts.factory.js
Labels: eve: release after merged

#1263 fix(): pass data through tpl in useBrick
  packages/brick-kit/src/BrickAsComponent.tsx
Labels: eve: release after merged

#1279 fix(): remember clear model i18n
  packages/sdk-scripts/src/loaders/loadService.ts
Labels: eve: release after merged

#1288 feat(): support prepending rules
  packages/webpack-config-factory/src/bricks/webpack.base.factory.js
Labels: eve: release after merged

#1293 feat(): support request use mock
  dll/editor-bricks-helper/manifest.snapshot.json
  etc/brick-kit.api.md
  etc/brick-types.api.md
  packages/brick-container/src/index.tsx
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/src/core/MockRegistry.spec.ts
  packages/brick-kit/src/core/MockRegistry.ts
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/index.ts
  packages/brick-types/src/manifest.ts
Labels: [bot]: updated dll manifest, [bot]: updating dll manifest, eve: release after merged

#1291 feat(): refine storyboard functions and expressions
  dll/editor-bricks-helper/manifest.snapshot.json
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.spec.ts
  packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.ts
  packages/brick-kit/src/core/WidgetFunctions.ts
  packages/brick-kit/src/internal/devtools.ts
  packages/brick-kit/src/internal/evaluate.spec.ts
  packages/brick-kit/src/internal/evaluate.ts
  packages/brick-kit/src/internal/getGeneralGlobals.ts
  packages/brick-kit/src/internal/proxyFactories.ts
  packages/brick-utils/src/index.ts
  packages/brick-utils/src/resolveContextConcurrently.ts
  packages/brick-utils/src/scanI18NInStoryboard.ts
  packages/brick-utils/src/scanPermissionActionsInStoryboard.spec.ts
  packages/brick-utils/src/scanPermissionActionsInStoryboard.ts
  packages/brick-utils/src/scanProcessorsInStoryboard.ts
  packages/brick-utils/src/visitStoryboard.spec.ts
  packages/brick-utils/src/visitStoryboard.ts
Labels: [bot]: updated dll manifest, eve: release after merged

#1300 fix(): refine visiting storyboard
  packages/brick-utils/src/visitStoryboard.spec.ts
  packages/brick-utils/src/visitStoryboard.ts
Labels: eve: release after merged

#1304 feat(): some adjustment for EasyopsEmpty's empty image
  etc/brick-kit.api.md
  packages/brick-kit/src/EasyopsEmpty/EasyopsEmpty.spec.tsx
  packages/brick-kit/src/EasyopsEmpty/EasyopsEmpty.tsx
  packages/brick-kit/src/images/big-empty-image.png
  packages/brick-kit/src/images/empty-image.png
Labels: eve: release after merged

#1309 feat(MockRegistry): update mocks data
  dll/editor-bricks-helper/manifest.snapshot.json
  etc/brick-kit.api.md
  etc/brick-types.api.md
  packages/brick-container/src/index.tsx
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/src/core/MockRegistry.spec.ts
  packages/brick-kit/src/core/MockRegistry.ts
  packages/brick-kit/src/index.ts
  packages/brick-types/src/manifest.ts
Labels: [bot]: updated dll manifest, eve: release after merged, [bot]: updated docs etc

#1306 fix(): modify style
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
Labels: eve: release after merged

#1312 fix(): style refactor
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/brick-container/src/styles/variables.css
Labels: eve: release after merged

#1321 feat(httpInterceptors): update mock url
  packages/brick-container/src/index.tsx
Labels: eve: release after merged

#1322 fix(): css variables
  packages/brick-container/src/styles/theme/dark.css
  packages/custom-antd-styles/src/var.less
Labels: eve: release after merged

#1320 chore(): change the empty images' format
  .size-limit.js
  packages/brick-container/webpack/common.js
  packages/brick-kit/rollup.config.js
  packages/brick-kit/src/EasyopsEmpty/EasyopsEmpty.spec.tsx
  packages/brick-kit/src/EasyopsEmpty/EasyopsEmpty.tsx
  packages/brick-kit/src/auth.spec.ts
  packages/brick-kit/src/images/big-empty-image.png
  packages/brick-kit/src/images/big-empty-image.svg
  packages/brick-kit/src/images/empty-image.png
  packages/brick-kit/src/images/empty-image.svg
Labels: eve: release after merged
