Repository easyops-cn/next-core, pull requests merged in 2021-07, with the labels that each got.

#692 Steve/story refactor
  dll/editor-bricks-helper/manifest.snapshot.json
  packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.spec.tsx
  packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.tsx
  packages/editor-bricks-helper/src/EditorBrickAsComponent/getEditorBrick.spec.ts
  packages/editor-bricks-helper/src/EditorBrickAsComponent/getEditorBrick.ts
  packages/editor-bricks-helper/src/assertions.spec.ts
  packages/editor-bricks-helper/src/assertions.ts
  packages/editor-bricks-helper/src/hooks/useSharedEditorMap.spec.tsx
  packages/editor-bricks-helper/src/hooks/useSharedEditorMap.ts
  packages/editor-bricks-helper/src/interfaces.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
Labels: eve: release after merged

#697 Steve/next
  dll/ace/CHANGELOG.md
  dll/editor-bricks-helper/CHANGELOG.md
  dll/react-dnd/CHANGELOG.md
  docker-compose.yml
  package.json
  packages/babel-preset-next/CHANGELOG.md
  packages/babel-preset-next/package.json
  packages/babel-preset-prismjs/package.json
  packages/babel-runtime-helpers/package.json
  packages/brick-container/CHANGELOG.md
  packages/brick-container/package.json
  packages/brick-dll/CHANGELOG.md
  packages/brick-dll/package.json
  packages/brick-http/CHANGELOG.md
  packages/brick-icons/CHANGELOG.md
  packages/brick-icons/package.json
  packages/brick-kit/CHANGELOG.md
  packages/brick-kit/package.json
  packages/brick-kit/src/bindListeners.spec.ts
  packages/brick-scripts/CHANGELOG.md
  packages/brick-scripts/package.json
  packages/brick-types/CHANGELOG.md
  packages/brick-utils/CHANGELOG.md
  packages/brick-utils/package.json
  packages/build-config-factory/CHANGELOG.md
  packages/build-config-factory/package.json
  packages/create-next-repo/package.json
  packages/dev-dependencies/CHANGELOG.md
  packages/dev-dependencies/package.json
  packages/dll-differ/package.json
  packages/easyops-analytics/CHANGELOG.md
  packages/easyops-illustrations/CHANGELOG.md
  packages/easyops-illustrations/package.json
  packages/editor-bricks-helper/CHANGELOG.md
  packages/eslint-config-next/CHANGELOG.md
  packages/eslint-config-next/package.json
  packages/fontawesome-library/CHANGELOG.md
  packages/next-docs/CHANGELOG.md
  packages/rollup-config-factory/CHANGELOG.md
  packages/rollup-config-factory/package.json
  packages/sdk-scripts/CHANGELOG.md
  packages/sdk-scripts/package.json
  packages/webpack-config-factory/package.json
  yarn.lock
Labels: eve: release after merged

#705 feat(): add deploy icons
  packages/brick-icons/src/icons/deploy/develop.svg
  packages/brick-icons/src/icons/deploy/prerelease.svg
  packages/brick-icons/src/icons/deploy/production.svg
  packages/brick-icons/src/icons/deploy/test.svg
Labels: eve: release after merged

#706 feat(): support sessionStorage.getItem,sessionStorage.setItem and SES…
  etc/brick-types.api.md
  packages/brick-kit/src/bindListeners.spec.ts
  packages/brick-kit/src/bindListeners.ts
  packages/brick-kit/src/core/Storage.spec.ts
  packages/brick-kit/src/core/Storage.ts
  packages/brick-kit/src/core/localStorage.spec.ts
  packages/brick-kit/src/core/localStorage.ts
  packages/brick-kit/src/evaluate.spec.ts
  packages/brick-kit/src/evaluate.ts
  packages/brick-types/src/manifest.ts
Labels: [bot]: updated docs etc, eve: release after merged

#718 feat: expand templates
  .size-limit.js
  packages/editor-bricks-helper/src/DropZone/DropZone.tsx
  packages/editor-bricks-helper/src/EditorContainer/EditorContainer.spec.tsx
  packages/editor-bricks-helper/src/EditorContainer/EditorContainer.tsx
  packages/editor-bricks-helper/src/EditorContainer/isCurrentTargetByClassName.spec.ts
  packages/editor-bricks-helper/src/EditorContainer/isCurrentTargetByClassName.ts
  packages/editor-bricks-helper/src/hooks/useBuilderGroupedChildNodes.spec.tsx
  packages/editor-bricks-helper/src/hooks/useBuilderGroupedChildNodes.ts
  packages/editor-bricks-helper/src/hooks/useBuilderMountPointChildNodes.spec.tsx
  packages/editor-bricks-helper/src/hooks/useBuilderMountPointChildNodes.ts
  packages/editor-bricks-helper/src/hooks/useBuilderNodeMountPoints.spec.tsx
  packages/editor-bricks-helper/src/hooks/useBuilderNodeMountPoints.ts
  packages/editor-bricks-helper/src/hooks/useBuilderParentNode.spec.tsx
  packages/editor-bricks-helper/src/hooks/useBuilderParentNode.ts
  packages/editor-bricks-helper/src/interfaces.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
  packages/editor-bricks-helper/src/internal/deleteNodeFromTree.ts
  packages/editor-bricks-helper/src/internal/expandTemplateEdges.spec.ts
  packages/editor-bricks-helper/src/internal/expandTemplateEdges.ts
  packages/editor-bricks-helper/src/internal/getAppendingNodesAndEdges.spec.ts
  packages/editor-bricks-helper/src/internal/getAppendingNodesAndEdges.ts
  packages/editor-bricks-helper/src/internal/getBuilderNode.spec.ts
  packages/editor-bricks-helper/src/internal/getBuilderNode.ts
  packages/editor-bricks-helper/src/internal/isParentExpandableTemplate.ts
  packages/editor-bricks-helper/src/internal/reorderBuilderEdges.spec.ts
  packages/editor-bricks-helper/src/internal/reorderBuilderEdges.ts
Labels: eve: release after merged

#725 feat(story): support parenthesized type
  packages/build-config-factory/src/generateBrickDocs.js
Labels: eve: release after merged

#726 Steve/expand tpl
  dll/editor-bricks-helper/manifest.snapshot.json
  packages/editor-bricks-helper/src/DropZone/DropZone.tsx
  packages/editor-bricks-helper/src/DropZone/getDropPosition.ts
  packages/editor-bricks-helper/src/DroppingStatusContext.ts
  packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.tsx
  packages/editor-bricks-helper/src/EditorContainer/EditorContainer.spec.tsx
  packages/editor-bricks-helper/src/EditorContainer/EditorContainer.tsx
  packages/editor-bricks-helper/src/SlotContainer/SlotContainer.tsx
  packages/editor-bricks-helper/src/hooks/useBuilderGroupedChildNodes.ts
  packages/editor-bricks-helper/src/hooks/useDroppingStatus.spec.tsx
  packages/editor-bricks-helper/src/hooks/useDroppingStatus.ts
  packages/editor-bricks-helper/src/index.ts
  packages/editor-bricks-helper/src/interfaces.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
  packages/editor-bricks-helper/src/internal/expandTemplateEdges.ts
  packages/editor-bricks-helper/src/internal/getAppendingNodesAndEdges.spec.ts
  packages/editor-bricks-helper/src/internal/getAppendingNodesAndEdges.ts
Labels: eve: release after merged

#734 Steve/context menu
  packages/editor-bricks-helper/src/DropZone/DropZone.module.css
  packages/editor-bricks-helper/src/DropZone/DropZone.tsx
  packages/editor-bricks-helper/src/DropZone/getDropPosition.ts
  packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.spec.tsx
  packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.tsx
  packages/editor-bricks-helper/src/EditorContainer/EditorContainer.module.css
  packages/editor-bricks-helper/src/EditorContainer/EditorContainer.spec.tsx
  packages/editor-bricks-helper/src/EditorContainer/EditorContainer.tsx
  packages/editor-bricks-helper/src/EditorContainer/isCurrentTargetByClassName.spec.ts
  packages/editor-bricks-helper/src/EditorContainer/isCurrentTargetByClassName.ts
  packages/editor-bricks-helper/src/internal/getAppendingNodesAndEdges.ts
Labels: eve: release after merged

#737 fix(serve): support to set local snippet packages
  packages/brick-container/serve/getEnv.js
  packages/brick-container/serve/getProxies.js
Labels: eve: release after merged

#738 Steve/expand tpl
  packages/editor-bricks-helper/src/internal/getAppendingNodesAndEdges.spec.ts
  packages/editor-bricks-helper/src/internal/getAppendingNodesAndEdges.ts
Labels: eve: release after merged

#740 fix(): disable dragging template internal nodes
  packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.spec.tsx
  packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.tsx
Labels: eve: release after merged

#751 feat(): unify builder node normalization
  dll/editor-bricks-helper/manifest.snapshot.json
  packages/brick-dll/manifest.snapshot.json
  packages/brick-utils/src/builder/assertions.spec.ts
  packages/brick-utils/src/builder/assertions.ts
  packages/brick-utils/src/builder/index.ts
  packages/brick-utils/src/builder/normalizeBuilderNode.spec.ts
  packages/brick-utils/src/builder/normalizeBuilderNode.ts
  packages/brick-utils/src/index.ts
  packages/editor-bricks-helper/src/assertions.ts
  packages/editor-bricks-helper/src/interfaces.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
  packages/editor-bricks-helper/src/internal/getBuilderNode.spec.ts
  packages/editor-bricks-helper/src/internal/getBuilderNode.ts
Labels: eve: release after merged

#757 feat(): support deepFreeze in brick-utils
  dll/editor-bricks-helper/manifest.snapshot.json
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/processors.ts
  packages/brick-utils/src/cook/CookVisitor.ts
  packages/brick-utils/src/cook/PrecookVisitor.ts
  packages/brick-utils/src/cook/cook.ts
  packages/brick-utils/src/cook/index.ts
  packages/brick-utils/src/cook/precook.ts
  packages/brick-utils/src/deepFreeze.spec.ts
  packages/brick-utils/src/deepFreeze.ts
  packages/brick-utils/src/index.ts
  packages/brick-utils/src/resolveContextConcurrently.ts
  packages/brick-utils/src/scanI18NInStoryboard.ts
  packages/brick-utils/src/scanPermissionActionsInStoryboard.ts
  packages/brick-utils/src/scanProcessorsInStoryboard.ts
  packages/editor-bricks-helper/src/internal/expandTemplateEdges.spec.ts
Labels: [bot]: updated dll manifest, eve: release after merged

#758 fix(builder): consider `transformFrom` as a yaml field
  packages/brick-utils/src/builder/normalizeBuilderNode.ts
Labels: eve: release after merged

#756 feat(): 支持多种获取特性开关的方式
  dll/editor-bricks-helper/manifest.snapshot.json
  etc/brick-kit.api.md
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/src/BrickWrapper.spec.tsx
  packages/brick-kit/src/BrickWrapper.tsx
  packages/brick-kit/src/__snapshots__/BrickWrapper.spec.tsx.snap
  packages/brick-kit/src/featuraFlags.spec.tsx
  packages/brick-kit/src/featureFlags.tsx
  packages/brick-kit/src/index.ts
Labels: [bot]: updated dll manifest, eve: release after merged

#765 refactor(BrickAsComponent): wrap with React.memo to avoid unnecessary…
  etc/brick-kit.api.md
  packages/brick-kit/src/BrickAsComponent.tsx
Labels: eve: release after merged

#766 fix(builder): fix `transformFrom` in brick nodes
  packages/brick-utils/src/builder/normalizeBuilderNode.ts
Labels: eve: release after merged

#764 fix(): refine feature flags
  packages/brick-kit/src/BrickWrapper.tsx
  packages/brick-kit/src/__snapshots__/BrickWrapper.spec.tsx.snap
  packages/brick-kit/src/featuraFlags.spec.tsx
Labels: eve: release after merged

#770 fix(): httpError style fix
  packages/brick-kit/src/handleHttpError.spec.tsx
  packages/brick-kit/src/handleHttpError.tsx
Labels: eve: release after merged

#772 fix(builder): update only id and instanceId after node stored
  packages/editor-bricks-helper/src/DropZone/reverseNormalize.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
Labels: eve: release after merged

#781 feat(): add route field for analysis
  packages/brick-kit/src/core/LocationContext.ts
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/core/__mocks__/LocationContext.ts
  packages/easyops-analytics/src/ApiAnalysis.spec.ts
  packages/easyops-analytics/src/ApiAnalysis.ts
Labels: eve: release after merged

#779 Williamcai/brick kit location context fallback to value when resolve is invalid
  packages/brick-kit/src/core/LocationContext.spec.ts
  packages/brick-kit/src/core/LocationContext.ts
  packages/brick-utils/src/resolveContextConcurrently.spec.ts
  packages/brick-utils/src/resolveContextConcurrently.ts
Labels: eve: release after merged

#785 fix(LocationContext): use hasOwnProperty to check if value exists
  packages/brick-kit/src/core/LocationContext.ts
Labels: eve: release after merged

#786 Steve/track ctx
  .size-limit.js
  dll/editor-bricks-helper/manifest.snapshot.json
  etc/brick-types.api.md
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/package.json
  packages/brick-kit/src/bindListeners.spec.ts
  packages/brick-kit/src/bindListeners.ts
  packages/brick-kit/src/core/LocationContext.spec.ts
  packages/brick-kit/src/core/LocationContext.ts
  packages/brick-kit/src/core/MessageDispatcher.spec.ts
  packages/brick-kit/src/core/MessageDispatcher.ts
  packages/brick-kit/src/core/listenOnTrackingContext.spec.ts
  packages/brick-kit/src/core/listenOnTrackingContext.ts
  packages/brick-kit/src/setProperties.spec.ts
  packages/brick-kit/src/setProperties.ts
  packages/brick-kit/src/websocket/interfaces/index.ts
  packages/brick-types/src/runtime.ts
  packages/brick-utils/src/index.ts
  packages/brick-utils/src/trackContext.spec.ts
  packages/brick-utils/src/trackContext.ts
Labels: eve: release after merged

#780 feat(menu): support injecting menu items into a menu group
  packages/brick-container/deploy/package.conf.yaml
  packages/brick-kit/src/core/menu.spec.ts
  packages/brick-kit/src/core/menu.ts
Labels: eve: release after merged

#800 fix(menu): allow injecting menu items in non-group menus
  packages/brick-kit/src/core/menu.spec.ts
  packages/brick-kit/src/core/menu.ts
Labels: eve: release after merged

#755 chore(micro_app_service): 去除brick和snippet导入开关
  packages/brick-container/tools/report_installed_brick_next_package.py
Labels: eve: release after merged

#802 feat(): support transforming data in properties of useBrick
  etc/brick-kit.api.md
  packages/brick-kit/src/BrickAsComponent.spec.tsx
  packages/brick-kit/src/BrickAsComponent.tsx
  packages/brick-kit/src/internal/getNextStateOfUseBrick.ts
  packages/brick-kit/src/setProperties.spec.ts
  packages/brick-kit/src/setProperties.ts
  packages/brick-kit/src/transformProperties.spec.ts
  packages/brick-kit/src/transformProperties.ts
Labels: eve: release after merged

#804 feat(): support tracking context in useBrick
  packages/brick-kit/src/BrickAsComponent.tsx
  packages/brick-kit/src/core/LocationContext.ts
  packages/brick-kit/src/internal/listenOnTrackingContext.spec.ts
  packages/brick-kit/src/internal/listenOnTrackingContext.ts
  packages/brick-kit/src/setProperties.spec.ts
  packages/brick-kit/src/setProperties.ts
  packages/brick-kit/src/transformProperties.spec.ts
  packages/brick-kit/src/transformProperties.ts
Labels: eve: release after merged

#810 fix(): transform useBrick.if lazyly inside useBrick.properties
  packages/brick-kit/src/BrickAsComponent.spec.tsx
  packages/brick-kit/src/internal/getNextStateOfUseBrick.ts
  packages/brick-kit/src/internal/setProperties.spec.ts
  packages/brick-kit/src/internal/setProperties.ts
  packages/brick-kit/src/transformProperties.spec.ts
Labels: eve: release after merged

#815 feat(): support lazy load of bricks
  etc/brick-kit.api.md
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/LazyBrickRegistry.spec.ts
  packages/brick-kit/src/core/LazyBrickRegistry.ts
  packages/brick-kit/src/core/Runtime.ts
  packages/brick-kit/src/core/interfaces.ts
  packages/brick-utils/src/getDllAndDepsOfStoryboard.spec.ts
  packages/brick-utils/src/getDllAndDepsOfStoryboard.ts
  packages/webpack-config-factory/src/bricks/webpack.base.factory.js
  packages/webpack-config-factory/src/bricks/webpack.prod.factory.js
Labels: eve: release after merged
