Repository easyops-cn/next-core, pull requests merged in 2021-06, with the labels that each got.

#565 feat(): brick:basic-bricks.menu-bar add testid Closes BRICK_STORE-2139
  packages/brick-kit/src/core/Bars/BaseBar.spec.ts
  packages/brick-kit/src/core/Bars/BaseBar.ts
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
Labels: eve: release after merged

#569 fix(): revert some babel plugins
  packages/babel-preset-next/index.js
  packages/babel-preset-next/package.json
Labels: eve: release after merged

#573 Steve/easy view
  packages/brick-container/serve/utils.js
  packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.module.css
  packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.tsx
Labels: eve: release after merged

#577 feat(brick-types): menuIcon.color support gradient color
  etc/brick-types.api.md
  packages/brick-types/src/menu.ts
Labels: eve: release after merged

#579 feat(brick-types): GradientColor support direction
  etc/brick-types.api.md
  packages/brick-types/src/menu.ts
Labels: eve: release after merged

#580 feat(): support to add bricks with properties
  packages/editor-bricks-helper/src/DropZone/processDrop.spec.ts
  packages/editor-bricks-helper/src/DropZone/processDrop.ts
  packages/editor-bricks-helper/src/interfaces.ts
Labels: eve: release after merged

#598 feat(): export useHighlightNodes
  dll/editor-bricks-helper/manifest.snapshot.json
  packages/editor-bricks-helper/src/index.ts
Labels: eve: release after merged

#603 fix(): add a resolution of @testing-library/dom
  packages/dev-dependencies/patch.js
  packages/dev-dependencies/patches/index.js
  packages/dev-dependencies/patches/updateResolutions.js
  packages/dev-dependencies/patches/updateResolutions.spec.js
Labels: eve: release after merged

#607 chore(): update rollup plugins
  packages/brick-utils/rollup.config.js
  packages/rollup-config-factory/package.json
  packages/rollup-config-factory/src/index.js
  yarn.lock
Labels: eve: release after merged

#609 fix(): fix syntax
  packages/build-config-factory/src/generateBrickDocs.js
Labels: eve: release after merged

#612 feat(evaluate): support I18N_TEXT(data)
  packages/brick-kit/src/evaluate.spec.ts
  packages/brick-kit/src/evaluate.ts
  packages/brick-kit/src/i18nText.spec.ts
  packages/brick-kit/src/i18nText.ts
Labels: eve: release after merged

#630 feat(): support to apply snippets
  etc/brick-types.api.md
  packages/brick-types/src/builder.ts
  packages/brick-types/src/index.ts
  packages/brick-types/src/snippet.ts
  packages/editor-bricks-helper/src/DropZone/DropZone.tsx
  packages/editor-bricks-helper/src/DropZone/processDrop.spec.ts
  packages/editor-bricks-helper/src/DropZone/processDrop.ts
  packages/editor-bricks-helper/src/interfaces.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
  packages/editor-bricks-helper/src/processors/getSortedIdsAfterDropped.spec.ts
  packages/editor-bricks-helper/src/processors/getSortedIdsAfterDropped.ts
Labels: eve: release after merged

#638 fix(): refine types for snippets
  etc/brick-types.api.md
  packages/brick-kit/src/i18nText.spec.ts
  packages/brick-types/src/builder.ts
Labels: eve: release after merged

#639 fix(): fix snippets.json
  packages/build-config-factory/src/generateSnippets.js
Labels: eve: release after merged

#643 feat(): support to apply page title
  dll/editor-bricks-helper/manifest.snapshot.json
  etc/brick-kit.api.md
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/src/core/Bars/AppBar.ts
  packages/brick-kit/src/core/Bars/BaseBar.ts
  packages/brick-kit/src/core/Bars/MenuBar.ts
  packages/brick-kit/src/core/Runtime.spec.ts
  packages/brick-kit/src/core/Runtime.ts
  packages/brick-kit/src/core/interfaces.ts
  packages/brick-kit/src/index.ts
  packages/brick-kit/src/useApplyPageTitle.spec.tsx
  packages/brick-kit/src/useApplyPageTitle.ts
Labels: eve: release after merged

#645 fix(): refine brick conf to brick node
  dll/editor-bricks-helper/manifest.snapshot.json
  packages/editor-bricks-helper/package.json
  packages/editor-bricks-helper/src/DropZone/getSnippetNodeDetail.ts
  packages/editor-bricks-helper/src/DropZone/processDrop.spec.ts
  packages/editor-bricks-helper/src/DropZone/processDrop.ts
  packages/editor-bricks-helper/src/DropZone/reverseNormalize.ts
Labels: [bot]: updated dll manifest

#659 fix(sdk-scripts): fix form data with ref fields
  packages/sdk-scripts/src/interface.ts
  packages/sdk-scripts/src/lib/ObjectType.ts
  packages/sdk-scripts/src/lib/TypeDefinition.ts
  packages/sdk-scripts/src/lib/UnionType.ts
  packages/sdk-scripts/src/loaders/__snapshots__/loadService.spec.ts.snap
  packages/sdk-scripts/yaml/api/cd/package/send_message_with_appendix.yaml
  packages/sdk-scripts/yaml/model/msgsender/send_message_with_appendix_request.yaml
Labels: eve: release after merged

#666 fix(builder): support to initialize alias of brick nodes
  packages/editor-bricks-helper/src/DropZone/getSnippetNodeDetail.ts
  packages/editor-bricks-helper/src/DropZone/processDrop.spec.ts
  packages/editor-bricks-helper/src/DropZone/processDrop.ts
  packages/editor-bricks-helper/src/interfaces.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
  packages/editor-bricks-helper/src/internal/getBuilderNode.spec.ts
  packages/editor-bricks-helper/src/internal/getBuilderNode.ts
Labels: eve: release after merged

#668 fix(): add types of layer type
  etc/brick-types.api.md
  packages/brick-types/src/builder.ts
Labels: [bot]: updated docs etc, eve: release after merged

#678 fix(): fix onReject when resolving context
  packages/brick-kit/src/core/Resolver.spec.ts
  packages/brick-kit/src/core/Resolver.ts
Labels: eve: release after merged
