Repository easyops-cn/next-core, pull requests merged in 2022-03, with the labels that each got.

#1571 fix(): fix i18n of moment
  packages/brick-container/src/i18n/index.ts
Labels: eve: release after merged

#1578 add v8 ui variables
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
Labels: eve: release after merged

#1579 feat(): add custom css variables
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
Labels: eve: release after merged

#1589 feat(): support export container data
  packages/brick-kit/src/core/LocationContext.ts
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/core/Runtime.ts
Labels: [bot]: updated dll manifest, eve: release after merged

#1597 fix(): fix get deps when brick package has no editors
  packages/brick-utils/src/getDllAndDepsOfStoryboard.spec.ts
  packages/brick-utils/src/getDllAndDepsOfStoryboard.ts
Labels: eve: release after merged

#1606 fix(): style modify
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/custom-antd-styles/src/select.less
Labels: eve: release after merged

#1605 feat(): support dropZone add Empty ClassName
  packages/editor-bricks-helper/src/DropZone/DropZone.module.css
  packages/editor-bricks-helper/src/DropZone/DropZone.tsx
  packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.tsx
  packages/editor-bricks-helper/src/SlotContainer/SlotContainer.tsx
Labels: eve: release after merged

#1610 fix(): anchor style
  packages/brick-container/src/styles/theme/default.css
Labels: eve: release after merged

#1611 feat(): support get widget editor brick
  packages/editor-bricks-helper/src/EditorBrickAsComponent/getEditorBrick.spec.ts
  packages/editor-bricks-helper/src/EditorBrickAsComponent/getEditorBrick.ts
Labels: eve: release after merged

#1616 fix(): style refine
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/custom-antd-styles/src/menu.less
Labels: eve: release after merged

#1626 fix(): switch dark theme
  dll/editor-bricks-helper/manifest.snapshot.json
  etc/brick-kit.api.md
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/index.ts
  packages/brick-kit/src/themAndMode.spec.tsx
  packages/brick-kit/src/themeAndMode.ts
  packages/custom-antd-styles/src/dropdown.less
  packages/custom-antd-styles/src/var.less
Labels: eve: release after merged

#1628 fix(): add several preview message types
  etc/brick-types.api.md
  packages/brick-types/src/preview.ts
Labels: eve: release after merged

#1633 fix(): theme icon
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-icons/src/icons/dark-theme.svg
  packages/brick-icons/src/icons/light-theme.svg
Labels: eve: release after merged

#1640 feat(): new util function: debounceByAnimationFrame
  dll/editor-bricks-helper/manifest.snapshot.json
  packages/brick-dll/manifest.snapshot.json
  packages/brick-utils/src/debounceByAnimationFrame.spec.ts
  packages/brick-utils/src/debounceByAnimationFrame.ts
  packages/brick-utils/src/index.ts
Labels: [bot]: updated dll manifest, eve: release after merged

#1645 fix(): fix snippet add bug
  packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
Labels: eve: release after merged

#1654 feat(): support console in storyboard functions
  packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.spec.ts
  packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.ts
  packages/brick-kit/src/internal/evaluate.spec.ts
  packages/brick-kit/src/internal/getGeneralGlobals.ts
  packages/storyboard-function-types/scripts/libs/general.js
Labels: eve: release after merged

#1651 feat(): support APP.getMenus
  dll/editor-bricks-helper/manifest.snapshot.json
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/src/core/LocationContext.spec.ts
  packages/brick-kit/src/core/LocationContext.ts
  packages/brick-kit/src/internal/devtools.spec.ts
  packages/brick-kit/src/internal/evaluate.spec.ts
  packages/brick-kit/src/internal/evaluate.ts
  packages/brick-kit/src/internal/menu.spec.ts
  packages/brick-kit/src/internal/menu.ts
  packages/brick-utils/src/index.ts
  packages/brick-utils/src/scanAppInStoryboard.spec.ts
  packages/brick-utils/src/scanAppInStoryboard.ts
Labels: [bot]: updated dll manifest, eve: release after merged

#1657 fix(): ignore `previewSettings` when building route node
  packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.spec.ts
  packages/brick-kit/src/internal/getGeneralGlobals.ts
  packages/brick-utils/src/builder/normalizeBuilderNode.spec.ts
  packages/brick-utils/src/builder/normalizeBuilderNode.ts
  packages/cook/src/__fixtures__/expressions.ts
  packages/cook/src/__fixtures__/negative/expressions.ts
  packages/cook/src/__snapshots__/cook.spec.ts.snap
  packages/supply/src/index.ts
Labels: eve: release after merged

#1658 feat(): move node up or down
  packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
Labels: eve: release after merged

#1666 fix(preview): add types for context menu on brick
  etc/brick-types.api.md
  packages/brick-types/src/preview.ts
Labels: eve: release after merged

#1674 feat(): adapt to the dark theme
  packages/custom-antd-styles/src/tree/mixin.less
Labels: eve: release after merged

#1675 chore(): fix styles
  packages/custom-antd-styles/src/tree/mixin.less
Labels: eve: release after merged

#1676 feat(): support updating storyboard on the fly
  etc/brick-kit.api.md
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/Runtime.ts
  packages/brick-kit/src/developHelper.ts
Labels: eve: release after merged, [bot]: updated docs etc

#1681 fix(): 替换插画图片(easyops-illustrations) Closes DESIGNER_ROUTINE-546
  packages/easyops-illustrations/src/images/default/browser-version-low-dark.png
  packages/easyops-illustrations/src/images/default/browser-version-low.png
  packages/easyops-illustrations/src/images/default/create-content-dark.png
  packages/easyops-illustrations/src/images/default/create-content.png
  packages/easyops-illustrations/src/images/default/no-content-dark.png
  packages/easyops-illustrations/src/images/default/no-content.png
  packages/easyops-illustrations/src/images/default/no-history-dark.png
  packages/easyops-illustrations/src/images/default/no-history.png
  packages/easyops-illustrations/src/images/default/search-empty-dark.png
  packages/easyops-illustrations/src/images/default/search-empty.png
  packages/easyops-illustrations/src/images/exception/http-403-dark.png
  packages/easyops-illustrations/src/images/exception/http-403.png
  packages/easyops-illustrations/src/images/exception/http-404-dark.png
  packages/easyops-illustrations/src/images/exception/http-404.png
  packages/easyops-illustrations/src/images/exception/http-500-dark.png
  packages/easyops-illustrations/src/images/exception/http-500.png
  packages/easyops-illustrations/src/images/feedback/exception-dark.png
  packages/easyops-illustrations/src/images/feedback/exception.png
  packages/easyops-illustrations/src/images/feedback/fail-dark.png
  packages/easyops-illustrations/src/images/feedback/fail.png
  packages/easyops-illustrations/src/images/feedback/info-dark.png
  packages/easyops-illustrations/src/images/feedback/info.png
  packages/easyops-illustrations/src/images/feedback/success-dark.png
  packages/easyops-illustrations/src/images/feedback/success.png
Labels: eve: release after merged

#1680 feat(): cache fetchMenu, and APP.getMenu change
  packages/brick-kit/src/internal/menu.ts
Labels: eve: release after merged

#1679 feat(): add MEDIA gloabl object and onMediaChange life cycle
  .size-limit.js
  __jest__/setup.ts
  etc/brick-types.api.md
  packages/brick-kit/src/core/LocationContext.spec.ts
  packages/brick-kit/src/core/LocationContext.ts
  packages/brick-kit/src/core/Router.spec.ts
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/internal/evaluate.spec.ts
  packages/brick-kit/src/internal/evaluate.ts
  packages/brick-kit/src/internal/mediaQuery.spec.ts
  packages/brick-kit/src/internal/mediaQuery.ts
  packages/brick-types/src/manifest.ts
Labels: eve: release after merged, [bot]: updated docs etc

#1682 feat(): APP.getMenu support scan template & routes
  packages/brick-kit/src/core/LocationContext.spec.ts
  packages/brick-kit/src/core/LocationContext.ts
Labels: [bot]: updated dll manifest, eve: release after merged

#1685 refactor(mediaQuery): rename size to breakpoint
  packages/brick-kit/src/core/LocationContext.spec.ts
  packages/brick-kit/src/internal/evaluate.spec.ts
  packages/brick-kit/src/internal/mediaQuery.spec.ts
  packages/brick-kit/src/internal/mediaQuery.ts
Labels: eve: release after merged

#1686 feat(): set active node
  dll/editor-bricks-helper/manifest.snapshot.json
  packages/editor-bricks-helper/src/hooks/useActiveNodeUid.spec.tsx
  packages/editor-bricks-helper/src/hooks/useActiveNodeUid.ts
  packages/editor-bricks-helper/src/index.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
Labels: [bot]: updated dll manifest, eve: release after merged

#1678 feat(): useProviderHook契约收集
  packages/webpack-config-factory/package.json
  packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
  packages/webpack-config-factory/src/bricks/webpack.contracts.factory.js
  yarn.lock
Labels: eve: release after merged
