Repository easyops-cn/next-core, pull requests merged in 2022-01, with the labels that each got.

#1328 fix(Router): render call scrollTo before life cycle handler
  packages/brick-kit/src/core/Router.ts
Labels: eve: release after merged

#1327 feat(MockRegistry): remove version in mock url
  dll/editor-bricks-helper/manifest.snapshot.json
  etc/brick-kit.api.md
  packages/brick-container/src/index.tsx
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/src/core/MockRegistry.spec.ts
  packages/brick-kit/src/core/MockRegistry.ts
  packages/brick-kit/src/index.ts
Labels: [bot]: updated dll manifest, eve: release after merged, [bot]: updated docs etc

#1330 Jojiang/theme
  .size-limit.js
  etc/brick-kit.api.md
  etc/brick-types.api.md
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/interfaces.ts
  packages/brick-types/src/manifest.ts
  packages/custom-antd-styles/src/checkbox/mixin.less
  packages/custom-antd-styles/src/var.less
Labels: eve: release after merged

#1337 feat(): expose types of builtins for storyboard functions
  packages/storyboard-function-types/.gitignore
  packages/storyboard-function-types/package.json
  packages/storyboard-function-types/scripts/libs/general.js
  packages/storyboard-function-types/scripts/libs/lodash.js
  packages/storyboard-function-types/scripts/libs/moment.js
  packages/storyboard-function-types/scripts/libs/pipes.js
  packages/storyboard-function-types/scripts/pre-build.js
  packages/storyboard-function-types/src/index.ts
  packages/storyboard-function-types/src/interfaces.ts
  packages/storyboard-function-types/tsconfig.json
Labels: eve: release after merged

#1338 fix(): fix `_.isEmpty(QUERY)`
  packages/brick-kit/src/internal/evaluate.spec.ts
  packages/brick-kit/src/internal/evaluate.ts
Labels: eve: release after merged

#1339 feat(): card style
  packages/brick-container/serve/getProxies.js
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/brick-container/src/styles/variables.css
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/internal/evaluate.ts
  packages/brick-kit/src/internal/getGeneralGlobals.spec.ts
  packages/brick-kit/src/internal/getGeneralGlobals.ts
  packages/custom-antd-styles/src/card.less
  packages/custom-antd-styles/src/var.less
Labels: eve: release after merged

#1340 feat(FlowApi): useMock in flow api
  .size-limit.js
  etc/brick-types.api.md
  packages/brick-kit/src/core/FlowApi.spec.ts
  packages/brick-kit/src/core/FlowApi.ts
  packages/brick-types/src/manifest.ts
Labels: [bot]: updating dll manifest, eve: release after merged, [bot]: updated docs etc

#1341 feat(): general-radio style
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/brick-container/src/styles/variables.css
  packages/custom-antd-styles/src/var.less
  packages/less-plugin-css-variables/src/LessReplacer.js
Labels: eve: release after merged

#1349 feat():component style
  dll/editor-bricks-helper/manifest.snapshot.json
  etc/brick-kit.api.md
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/index.ts
  packages/brick-kit/src/themAndMode.spec.tsx
  packages/brick-kit/src/themeAndMode.ts
  packages/custom-antd-styles/src/var.less
Labels: eve: release after merged

#1368 fix(): do not depend on next_builder_service
  packages/brick-container/deploy/package.conf.yaml
Labels: eve: release after merged

#1370 feat(): menu add href field
  packages/brick-utils/src/builder/normalizeMenu.ts
Labels: eve: release after merged

#1371 Jojiang/theme
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/brick-container/src/styles/variables.css
  packages/custom-antd-styles/src/legacy-form.less
  packages/custom-antd-styles/src/pagination.less
  packages/custom-antd-styles/src/table.less
  packages/custom-antd-styles/src/var.less
Labels: eve: release after merged

#1375 Jojiang/theme
  packages/brick-container/scripts/pre-build.js
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/custom-antd-styles/src/var.less
Labels: eve: release after merged

#1379 Jojiang/theme
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/custom-antd-styles/src/button.less
  packages/custom-antd-styles/src/radio.less
  packages/custom-antd-styles/src/table.less
Labels: eve: release after merged

#1385 fix(): style fix
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/custom-antd-styles/src/table.less
Labels: eve: release after merged

#1390 fix(): fix styles and replace css variables
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/custom-antd-styles/src/transfer.less
Labels: eve: release after merged

#1391 Jojiang/theme
  packages/brick-container/src/styles/antd.less
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/custom-antd-styles/src/modal.less
  packages/custom-antd-styles/src/var.less
Labels: eve: release after merged

#1399 feat(): add icon
  .size-limit.js
  packages/brick-icons/src/icons/cmdb/permission-instance-create.svg
  packages/brick-icons/src/icons/cmdb/permission-instance-delete.svg
  packages/brick-icons/src/icons/cmdb/permission-instance-edit.svg
  packages/brick-icons/src/icons/cmdb/permission-instance-export.svg
  packages/brick-icons/src/icons/cmdb/permission-instance-interview.svg
  packages/brick-icons/src/icons/cmdb/permission-instance-record.svg
Labels: eve: release after merged

#1402 feat(): move to colored-common
  packages/brick-icons/src/icons/colored-common/permission-instance-create.svg
  packages/brick-icons/src/icons/colored-common/permission-instance-delete.svg
  packages/brick-icons/src/icons/colored-common/permission-instance-edit.svg
  packages/brick-icons/src/icons/colored-common/permission-instance-export.svg
  packages/brick-icons/src/icons/colored-common/permission-instance-interview.svg
  packages/brick-icons/src/icons/colored-common/permission-instance-record.svg
Labels: eve: release after merged

#1407 chore(): replace icons
  packages/brick-icons/src/icons/colored-common/cmdb-instance-create.svg
  packages/brick-icons/src/icons/colored-common/cmdb-instance-delete.svg
  packages/brick-icons/src/icons/colored-common/cmdb-instance-edit.svg
  packages/brick-icons/src/icons/colored-common/cmdb-instance-export.svg
  packages/brick-icons/src/icons/colored-common/cmdb-instance-interview.svg
  packages/brick-icons/src/icons/colored-common/cmdb-instance-record.svg
  packages/brick-icons/src/icons/colored-common/permission-instance-create.svg
  packages/brick-icons/src/icons/colored-common/permission-instance-delete.svg
  packages/brick-icons/src/icons/colored-common/permission-instance-edit.svg
  packages/brick-icons/src/icons/colored-common/permission-instance-export.svg
  packages/brick-icons/src/icons/colored-common/permission-instance-interview.svg
  packages/brick-icons/src/icons/colored-common/permission-instance-record.svg
Labels: eve: release after merged

#1408 fix(): fix history push in standalone apps
  packages/brick-kit/src/internal/historyExtended.spec.ts
  packages/brick-kit/src/internal/historyExtended.ts
Labels: eve: release after merged

#1409 feat(): support css variables of rank table
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
Labels: eve: release after merged

#1410 feat(): support css variables of chart axis
  packages/brick-container/src/styles/theme/default.css
Labels: eve: release after merged

#1419 feat(): use css variables for new theme colors
  packages/brick-container/scripts/pre-build.js
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/brick-container/src/styles/variables.css
  packages/brick-kit/src/internal/applyColorTheme.spec.ts
  packages/color-theme/src/index.spec.ts
  packages/color-theme/src/index.ts
  packages/custom-antd-styles/src/var.less
Labels: eve: release after merged

#1421 feat(): dashboard style
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
Labels: eve: release after merged

#1423 fix(): chart tooltip
  packages/brick-container/src/styles/theme/default.css
Labels: eve: release after merged

#1426 Jojiang/theme
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/custom-antd-styles/src/input.less
  packages/custom-antd-styles/src/select.less
  packages/custom-antd-styles/src/tag.less
Labels: eve: release after merged

#1430 fix(): support connect remote in standalone app
  packages/brick-container/serve/getProxies.js
  packages/brick-container/serve/serveLocal.js
  packages/brick-container/serve/utils.js
Labels: eve: release after merged

#1435 fix(): fix remote asset root
  packages/brick-container/serve/getProxies.js
Labels: eve: release after merged

#1434 fix(): refine css
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/custom-antd-styles/src/date-picker.less
  packages/custom-antd-styles/src/radio.less
  packages/custom-antd-styles/src/tag.less
Labels: eve: release after merged

#1460 fix(): fix the bug that the svg files cannot be displayed completely …
  packages/brick-kit/src/EasyopsEmpty/EasyopsEmpty.tsx
  packages/brick-kit/src/EasyopsEmpty/EmptySvg.tsx
  packages/brick-kit/src/images/big-empty-image.svg
  packages/brick-kit/src/images/empty-image.svg
Labels: eve: release after merged

#1467 fix(): empty image
  .size-limit.js
  packages/brick-kit/src/EasyopsEmpty/EasyopsEmpty.spec.tsx
  packages/brick-kit/src/EasyopsEmpty/EmptySvg.tsx
Labels: eve: release after merged
