Repository easyops-cn/next-core, pull requests merged in 2022-05, with the labels that each got.

#1776 fix(useBrick): fix update error
  packages/brick-kit/src/BrickAsComponent.spec.tsx
  packages/brick-kit/src/BrickAsComponent.tsx
Labels: eve: release after merged

#1787 fix(): fix use brick with template
  etc/brick-types.api.md
  packages/brick-kit/src/BrickAsComponent.spec.tsx
  packages/brick-kit/src/BrickAsComponent.tsx
  packages/brick-kit/src/core/CustomTemplates/__snapshots__/expandCustomTemplate.spec.ts.snap
  packages/brick-kit/src/core/CustomTemplates/constants.ts
  packages/brick-kit/src/core/CustomTemplates/expandCustomTemplate.ts
  packages/brick-kit/src/core/CustomTemplates/setupTemplateProxy.ts
  packages/brick-kit/src/core/CustomTemplates/setupUseBrickInTemplate.spec.ts
  packages/brick-kit/src/core/CustomTemplates/setupUseBrickInTemplate.ts
  packages/brick-kit/src/internal/setProperties.spec.ts
  packages/brick-kit/src/internal/setProperties.ts
  packages/brick-types/src/manifest.ts
Labels: eve: release after merged

#1790 test(): fix test warnings
  package.json
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/src/hooks/useProvider/useProvider.spec.tsx
  packages/brick-kit/src/themAndMode.spec.tsx
  packages/brick-utils/src/scanAppInStoryboard.spec.ts
  packages/easyops-analytics/src/userAnalytics.spec.ts
  yarn.lock
Labels: [bot]: updated dll manifest

#1800 fix(): ignore screenshot in builder nodes
  packages/brick-utils/src/builder/normalizeBuilderNode.spec.ts
  packages/brick-utils/src/builder/normalizeBuilderNode.ts
Labels: eve: release after merged

#1810 Next
  dll/ace/CHANGELOG.md
  dll/d3/CHANGELOG.md
  dll/echarts/CHANGELOG.md
  dll/editor-bricks-helper/CHANGELOG.md
  dll/react-dnd/CHANGELOG.md
  docker-compose.yml
  jest.config.js
  package.json
  packages/babel-preset-next/CHANGELOG.md
  packages/babel-preset-next/package.json
  packages/babel-preset-prismjs/CHANGELOG.md
  packages/babel-runtime-helpers/CHANGELOG.md
  packages/brick-container/CHANGELOG.md
  packages/brick-container/package.json
  packages/brick-dll/CHANGELOG.md
  packages/brick-dll/package.json
  packages/brick-icons/CHANGELOG.md
  packages/brick-kit/CHANGELOG.md
  packages/brick-kit/package.json
  packages/brick-scripts/CHANGELOG.md
  packages/brick-scripts/package.json
  packages/brick-types/CHANGELOG.md
  packages/brick-utils/CHANGELOG.md
  packages/brick-utils/package.json
  packages/build-config-factory/CHANGELOG.md
  packages/build-next-libs/CHANGELOG.md
  packages/build-next-libs/package.json
  packages/cook/CHANGELOG.md
  packages/cook/package.json
  packages/create-next-repo/CHANGELOG.md
  packages/create-next-repo/package.json
  packages/dev-dependencies/CHANGELOG.md
  packages/dev-dependencies/package.json
  packages/dll-differ/CHANGELOG.md
  packages/easyops-analytics/CHANGELOG.md
  packages/easyops-illustrations/CHANGELOG.md
  packages/easyops-illustrations/package.json
  packages/editor-bricks-helper/CHANGELOG.md
  packages/eslint-config-next/CHANGELOG.md
  packages/eslint-config-next/package.json
  packages/fontawesome-library/CHANGELOG.md
  packages/jest-config-factory/CHANGELOG.md
  packages/jest-config-factory/src/index.js
  packages/next-docs/CHANGELOG.md
  packages/pipes/CHANGELOG.md
  packages/rollup-config-factory/CHANGELOG.md
  packages/rollup-config-factory/package.json
  packages/sdk-scripts/CHANGELOG.md
  packages/sdk-scripts/package.json
  packages/storyboard-function-types/CHANGELOG.md
  packages/supply/CHANGELOG.md
  packages/webpack-config-factory/CHANGELOG.md
  packages/webpack-config-factory/package.json
  yarn.lock
Labels: eve: release after merged

#1811 feat(): support mocking global date
  .size-limit.js
  declarations/global.d.ts
  packages/brick-container/package.json
  packages/brick-container/serve/getEnv.js
  packages/brick-container/serve/serve.js
  packages/brick-container/src/index.ejs
  packages/brick-container/src/index.tsx
  packages/brick-container/webpack/common.js
  yarn.lock
Labels: eve: release after merged

#1812 Sailorshe/support mock method
  etc/brick-kit.api.md
  etc/brick-types.api.md
  packages/brick-container/src/index.tsx
  packages/brick-kit/src/core/MockRegistry.spec.ts
  packages/brick-kit/src/core/MockRegistry.ts
  packages/brick-types/src/manifest.ts
Labels: [bot]: updating dll manifest, eve: release after merged, [bot]: updated docs etc

#1819 feat(mock): update mock rule
  packages/brick-kit/src/core/MockRegistry.spec.ts
  packages/brick-kit/src/core/MockRegistry.ts
Labels: eve: release after merged

#1827 Next
  package.json
  packages/dev-dependencies/package.json
  yarn.lock
Labels: eve: release after merged

#1834 fix(general-select): 修改select样式
  packages/custom-antd-styles/src/select.less
Labels: eve: release after merged

#1855 feat(): support lifeCycle.onIntersectionChange
  etc/brick-types.api.md
  packages/brick-kit/src/core/LocationContext.spec.ts
  packages/brick-kit/src/core/LocationContext.ts
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/core/__mocks__/LocationContext.ts
  packages/brick-types/src/manifest.ts
Labels: [bot]: updated docs etc

#1866 fix(): theme dark
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/brick-kit/src/internal/bindListeners.ts
  packages/custom-antd-styles/src/message.less
Labels: eve: release after merged
