Repository easyops-cn/next-core, pull requests merged in 2022-08, with the labels that each got.

#2056 feat(): support local source change builderData
  etc/brick-kit.api.md
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/Runtime.ts
  packages/brick-kit/src/developHelper.ts
  packages/editor-bricks-helper/src/interfaces.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
Labels: [bot]: updated dll manifest, eve: release after merged

#2068 fix():修复ip正则校验规则，补充校验失败默认提示信息
  packages/brick-kit/src/core/CustomForms/ExpandCustomForm.spec.ts
  packages/brick-kit/src/core/CustomForms/ExpandCustomForm.ts
Labels: eve: release after merged

#2071 feat(): support INSTALLED_APPS in standalone mode
  dll/editor-bricks-helper/manifest.snapshot.json
  etc/brick-types.api.md
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/package.json
  packages/brick-kit/src/core/Router.spec.ts
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/core/Runtime.spec.ts
  packages/brick-kit/src/core/Runtime.ts
  packages/brick-kit/src/internal/getStandaloneInstalledApps.spec.ts
  packages/brick-kit/src/internal/getStandaloneInstalledApps.ts
  packages/brick-types/src/manifest.ts
  packages/brick-utils/src/index.ts
  packages/brick-utils/src/scanInstalledAppsInStoryboard.spec.ts
  packages/brick-utils/src/scanInstalledAppsInStoryboard.ts
  yarn.lock
Labels: [bot]: updated dll manifest

#2082 feat(): support updateNode update edges
  packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
Labels: eve: release after merged

#2080 Jimmy/standalone/settings and menus
  etc/brick-types.api.md
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/standaloneBootstrap.spec.ts
  packages/brick-kit/src/core/standaloneBootstrap.ts
  packages/brick-types/src/manifest.ts
Labels: [bot]: updated dll manifest, eve: release after merged

#2087 feat(): support drag snippet not update builder data
  packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
Labels: eve: release after merged

#2090 Steve/fix preview
  packages/brick-container/serve/getProxies.js
  packages/brick-container/serve/serve.js
  packages/brick-kit/src/core/Router.spec.ts
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/internal/mergePreviewRoutes.spec.ts
  packages/brick-kit/src/internal/mergePreviewRoutes.ts
Labels: eve: release after merged

#2091 feat(): update workbenchTree Drag move
  packages/editor-bricks-helper/src/interfaces.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
Labels: eve: release after merged

#2095 feat(http): add match-api-cache event
  packages/brick-container/src/index.tsx
  packages/brick-http/src/http.spec.ts
  packages/brick-http/src/http.ts
Labels: eve: release after merged

#2096 fix(): fix post message origin
  packages/brick-container/src/index.tsx
Labels: eve: release after merged

#2097 fix(http): post message error
  packages/brick-container/src/index.tsx
Labels: eve: release after merged

#2100 fix(http): fix sender error
  packages/brick-container/src/index.tsx
Labels: eve: release after merged

#2101 fix(): ignore emitting if devtools is not presented
  packages/brick-kit/src/internal/devtools.spec.ts
  packages/brick-kit/src/internal/devtools.ts
Labels: eve: release after merged

#2103 Steve/public cdn
  cypress.config.ts
  cypress/e2e/404.spec.js
  declarations/global.d.ts
  packages/brick-container/serve/getEnv.js
  packages/brick-container/serve/getProxies.js
  packages/brick-container/serve/index.js
  packages/brick-container/serve/serve.js
  packages/brick-container/serve/serveLocal.js
  packages/brick-container/src/index.ejs
  packages/brick-container/webpack/common.js
  packages/webpack-config-factory/src/bricks/webpack.base.factory.js
Labels: eve: release after merged

#2108 chore():add sdk:form-builder-service-sdk
  packages/public-scoped-sdk/index.js
Labels: eve: release after merged

#2109 Steve/allow preview localhost
  packages/brick-container/serve/getProxies.js
  packages/brick-container/src/index.tsx
Labels: eve: release after merged

#2111 fix(): fix jest migrations when no relevant files
  packages/dev-dependencies/patches/migrateLazyBricksWithJest.js
  packages/dev-dependencies/patches/migrateLazyBricksWithJest.spec.js
Labels: eve: release after merged

#2117 fix(): move error
  packages/editor-bricks-helper/src/interfaces.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
  packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
  packages/editor-bricks-helper/src/internal/getObjectIdByNode.spec.ts
  packages/editor-bricks-helper/src/internal/getObjectIdByNode.ts
Labels: eve: release after merged

#2123 fix(): refine contract building
  packages/webpack-config-factory/src/bricks/webpack.contracts.factory.js
Labels: eve: release after merged

#2125 feat(): support loading gltf
  packages/webpack-config-factory/src/bricks/webpack.base.factory.js
  packages/webpack-config-factory/src/loaders/gltf-loader.js
  packages/webpack-config-factory/src/loaders/utils.js
Labels: eve: release after merged

#2128 Steve/fix menu
  CONTRIBUTING.md
  packages/brick-container/serve/getEnv.js
  packages/brick-container/serve/getProxies.js
  packages/brick-container/serve/serve.js
  packages/brick-container/serve/serveLocal.js
  packages/brick-container/webpack/common.js
  packages/brick-container/webpack/dev.js
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/LocationContext.spec.ts
  packages/brick-kit/src/core/LocationContext.ts
  packages/brick-kit/src/core/standaloneBootstrap.ts
  packages/brick-kit/src/internal/menu.spec.ts
  packages/brick-kit/src/internal/menu.ts
Labels: eve: release after merged

#2126 feat(): http support crsf token
  etc/brick-types.api.md
  packages/brick-container/src/index.tsx
  packages/brick-kit/src/auth.ts
  packages/brick-types/src/manifest.ts
Labels: eve: release after merged

#2132 fix(handleHttpError): 修复请求报错msg超出弹窗的问题 refs INSTANCE-2681
  packages/brick-kit/src/handleHttpError.spec.tsx
  packages/brick-kit/src/handleHttpError.tsx
Labels: eve: release after merged

#2133 Revert "fix(handleHttpError): 修复请求报错msg超出弹窗的问题 refs INSTANCE-2681"
  packages/brick-kit/src/handleHttpError.spec.tsx
  packages/brick-kit/src/handleHttpError.tsx
Labels: eve: release after merged

#2137 fix(): fulfill i18n only when loading injected menus
  .size-limit.js
  etc/brick-types.api.md
  packages/brick-container/deploy/package.conf.yaml
  packages/brick-kit/package.json
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/internal/menu.spec.ts
  packages/brick-kit/src/internal/menu.ts
  packages/brick-types/src/manifest.ts
  yarn.lock
Labels: eve: release after merged

#2140 feat(): support lazy context
  dll/editor-bricks-helper/manifest.snapshot.json
  etc/brick-types.api.md
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/src/core/LocationContext.ts
  packages/brick-kit/src/core/Resolver.spec.ts
  packages/brick-kit/src/core/Resolver.ts
  packages/brick-kit/src/core/StoryboardContext.spec.ts
  packages/brick-kit/src/core/StoryboardContext.ts
  packages/brick-kit/src/internal/bindListeners.spec.ts
  packages/brick-kit/src/internal/bindListeners.ts
  packages/brick-types/src/manifest.ts
  packages/brick-types/src/runtime.ts
  packages/brick-utils/src/track.spec.ts
  packages/brick-utils/src/track.ts
Labels: [bot]: updated dll manifest, eve: release after merged

#2149 fix(): preview error when legacy was iframe
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
Labels: eve: release after merged

#2151 fix(): preview route render error
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
Labels: eve: release after merged

#2157 feat(easyops-analytics): support more metric
  packages/easyops-analytics/src/ApiAnalysis.spec.ts
  packages/easyops-analytics/src/ApiAnalysis.ts
Labels: eve: release after merged

#2152 feat(): support bundling menu with i18n
  etc/brick-types.api.md
  packages/brick-kit/src/i18n/index.ts
  packages/brick-kit/src/internal/evaluate.spec.ts
  packages/brick-kit/src/internal/evaluate.ts
  packages/brick-kit/src/internal/getGeneralGlobals.ts
  packages/brick-kit/src/internal/menu.spec.ts
  packages/brick-kit/src/internal/menu.ts
  packages/brick-kit/src/internal/setProperties.ts
  packages/brick-types/src/manifest.ts
  packages/brick-types/src/menu.ts
  packages/brick-types/src/runtime.ts
Labels: eve: release after merged

#2158 feat(brick-container): expose getHistory and getBasePath on window fo…
  packages/brick-container/src/index.tsx
Labels: eve: release after merged

#2159 Alex/dsdf
  packages/easyops-analytics/src/ApiAnalysis.spec.ts
  packages/easyops-analytics/src/ApiAnalysis.ts
Labels: eve: release after merged

#2164 fix(easyops-analytics): support more metric
  packages/easyops-analytics/src/ApiAnalysis.spec.ts
  packages/easyops-analytics/src/ApiAnalysis.ts
Labels: eve: release after merged

#2168 fix(): drop support for related apps
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/Router.spec.ts
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/core/Runtime.ts
Labels: eve: release after merged, [bot]: updated docs etc

#2169 feat(): support visual builder favicon
  packages/brick-icons/src/icons/visual-builder.svg
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/Router.spec.ts
  packages/brick-kit/src/core/Router.ts
Labels: eve: release after merged

#2172 fix(): remove dead code
  etc/brick-kit.api.md
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/Runtime.ts
  packages/brick-kit/src/core/interfaces.ts
  packages/cook/src/cook.ts
Labels: [bot]: updated docs etc

#2175 fix(): fix style
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
Labels: eve: release after merged
