Repository easyops-cn/next-core, pull requests merged in 2022-04, with the labels that each got.

#1687 fix(): use latest version of core-js for babel preset-env
  .size-limit.js
  packages/babel-preset-next/index.js
Labels: eve: release after merged

#1690 feat(): support re-registering custom templates
  packages/brick-kit/src/core/CustomTemplates/expandCustomTemplate.spec.ts
  packages/brick-kit/src/core/CustomTemplates/registerCustomTemplate.ts
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
Labels: eve: release after merged

#1694 fix(easyops-illustrations): 替换插画图片 Closes DESIGNER_ROUTINE-546
  packages/easyops-illustrations/src/images/default/browser-version-low-dark.png
  packages/easyops-illustrations/src/images/default/create-content-dark.png
  packages/easyops-illustrations/src/images/default/no-content-dark.png
  packages/easyops-illustrations/src/images/default/no-history-dark.png
  packages/easyops-illustrations/src/images/default/search-empty-dark.png
  packages/easyops-illustrations/src/images/exception/http-403-dark.png
  packages/easyops-illustrations/src/images/exception/http-404-dark.png
  packages/easyops-illustrations/src/images/exception/http-500-dark.png
Labels: eve: release after merged

#1695 feat(): support previewing template by settings
  .size-limit.js
  etc/brick-kit.api.md
  packages/brick-container/src/index.tsx
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/core/Runtime.ts
  packages/brick-kit/src/developHelper.ts
Labels: eve: release after merged, [bot]: updated docs etc

#1697 fix(): no need to add a placeholder for template preview
  packages/brick-kit/src/core/Router.ts
Labels: eve: release after merged

#1699 chore(): reset css for layout-business
  packages/custom-antd-styles/src/form.less
Labels: eve: release after merged

#1702 fix(): 自定义rate的颜色 refs BRICK_STORE-2660
  packages/brick-container/src/styles/antd.less
  packages/custom-antd-styles/src/rate.less
Labels: eve: release after merged

#1703 fix(): fix getMenu later
  packages/brick-kit/src/core/LocationContext.spec.ts
  packages/brick-kit/src/core/LocationContext.ts
Labels: eve: release after merged

#1714 Steve/no slot for bg bricks
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/LocationContext.ts
  packages/brick-kit/src/core/Router.ts
Labels: eve: release after merged

#1716 fix(): useProvider hook 支持query查询provider
  packages/brick-kit/src/hooks/useProvider/useProvider.ts
Labels: eve: release after merged

#1718 fix(): reload bootstrap again when loading bricks failed
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
Labels: eve: release after merged

#1719 fix(general-button): 适配dark模式下按钮背景色
  packages/brick-container/src/styles/theme/dark.css
Labels: eve: release after merged

#1721 fix(template-preview): support setting lifeCycle and events
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
Labels: eve: release after merged

#1722 fix(): put template preview route before others
  packages/brick-kit/src/core/Router.ts
Labels: eve: release after merged

#1723 fix(): support setting targetRef as array
  etc/brick-types.api.md
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/internal/bindListeners.spec.ts
  packages/brick-kit/src/internal/bindListeners.ts
  packages/brick-types/src/manifest.ts
  packages/editor-bricks-helper/src/processors/getRelatedNodesBasedOnEvents.ts
Labels: eve: release after merged

#1724 Kehua/master/fix dark mode
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-icons/src/icons/colored-common/expansion-1.svg
  packages/custom-antd-styles/src/modal.less
  packages/custom-antd-styles/src/radio.less
  packages/custom-antd-styles/src/spin.less
Labels: eve: release after merged

#1725 fix(): put template preview route between specific ones and others
  packages/brick-kit/src/core/Router.ts
Labels: eve: release after merged

#1728 fix(general-radio): 修改颜色变量
  packages/custom-antd-styles/src/radio.less
Labels: eve: release after merged

#1730 fix(): 修改颜色变量指向
  packages/brick-container/src/styles/theme/dark.css
Labels: eve: release after merged

#1733 fix(): card style
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
Labels: eve: release after merged

#1739 fix(getMenu): fix menu lose
  packages/brick-kit/src/internal/menu.ts
Labels: eve: release after merged

#1742 fix(): fix menu in iframe
  etc/brick-types.api.md
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/internal/misc.spec.ts
  packages/brick-kit/src/internal/misc.ts
  packages/brick-types/src/runtime.ts
Labels: eve: release after merged

#1758 fix(): adopt testing-library instead of enzyme
  packages/brick-scripts/src/loaders/__snapshots__/loadTemplate.spec.ts.snap
  packages/brick-scripts/src/questions/askTargetType.ts
  packages/brick-scripts/template/brick/$PascalBrickName$.spec.tsx
  packages/brick-scripts/template/brick/$PascalBrickName$.tsx
Labels: eve: release after merged

#1759 feat():告警等级颜色修改等优化 Closes SERVICE_OBSERVE-1319
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
Labels: eve: release after merged

#1762 Next
  package.json
  packages/brick-container/package.json
  packages/dev-dependencies/package.json
  packages/eslint-config-next/package.json
  yarn.lock
Labels: eve: release after merged

#1763 fix(): override mount point for snippets
  packages/editor-bricks-helper/src/internal/getAppendingNodesAndEdges.ts
Labels: eve: release after merged

#1764 fix(): mock _.uniqueId in storyboard functions
  packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.spec.ts
  packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.ts
  packages/supply/src/index.ts
Labels: eve: release after merged

#1765 feat(): support snippet preview
  etc/brick-kit.api.md
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/core/Runtime.ts
  packages/brick-kit/src/developHelper.ts
Labels: [bot]: updating dll manifest, eve: release after merged, [bot]: updated docs etc

#1773 fix(): fix types of BrickWrapper
  etc/brick-kit.api.md
  packages/brick-kit/src/BrickWrapper.tsx
Labels: eve: release after merged

#1775 fix(): fix transformModulePatterns
  packages/jest-config-factory/src/index.js
Labels: eve: release after merged
