Repository easyops-cn/next-core, pull requests merged in 2023-05, with the labels that each got.

#3014 fix(): fix set props of useBrick
  packages/brick-kit/src/internal/setProperties.spec.ts
  packages/brick-kit/src/internal/setProperties.ts
Labels: eve: release after merged

#3015 feat(): support using v3 bricks in v2 container
  .size-limit.js
  packages/brick-dll/webpack.dll.js
  packages/brick-kit/package.json
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-utils/src/getDllAndDepsOfStoryboard.spec.ts
  packages/brick-utils/src/getDllAndDepsOfStoryboard.ts
  yarn.lock
Labels: eve: release after merged

#3016 Steve/v3-refine-utils
  bricks/e2e/src/data-providers/return-by-timeout.ts
  packages/build-next-bricks/src/EmitBricksJsonPlugin.js
  packages/runtime/src/internal/data/DataStore.spec.ts
  packages/runtime/src/internal/data/FlowApiProvider.ts
  packages/utils/src/general/createProviderClass.spec.ts
  packages/utils/src/general/createProviderClass.ts
  packages/utils/src/general/index.ts
  packages/utils/src/general/unwrapProvider.spec.ts
  packages/utils/src/general/unwrapProvider.ts
  packages/utils/src/storyboard/index.ts
Labels: eve: release after merged

#3019 chore(): add icons
  packages/brick-icons/src/icons/colored-big-screen/app.svg
  packages/brick-icons/src/icons/colored-big-screen/cluster.svg
  packages/brick-icons/src/icons/colored-big-screen/host.svg
  packages/brick-icons/src/icons/colored-big-screen/pod.svg
Labels: eve: release after merged

#3024 fix(): should also report nt packges
  packages/brick-container/tools/report_installed_brick_next_package.py
Labels: eve: release after merged

#3027 Steve/v3-build-brick-metadata
  .gitignore
  bricks/demo-widgets/package.json
  bricks/e2e/package.json
  packages/build-next-bricks/bin/build-next-bricks.js
  packages/build-next-bricks/package.json
  packages/build-next-bricks/src/generateMetadata.js
  packages/build-next-bricks/template/.pkgbuild/PKGBUILD
  packages/build-next-bricks/template/deploy/install_postscript.sh
  packages/build-next-bricks/template/deploy/update_postscript.sh
  packages/build-next-bricks/template/deploy/update_prescript.sh
Labels: eve: release after merged

#3029 fix(): allow v2 bricks to be used in v3 container
  packages/brick-scripts/template/bricks-pkg/deploy-default/package.conf.yaml
  packages/build-config-factory/src/generateDeps.js
  packages/build-config-factory/src/post-build.js
Labels: eve: release after merged

#3031 fix(): fix extract when renovate is enabled in root
  packages/dev-dependencies/extract.js
Labels: eve: release after merged

#3034 fix(): ignore non-plain object in props when setup useBrick
  packages/brick-kit/src/core/CustomTemplates/setupUseBrickInTemplate.ts
  packages/brick-kit/src/internal/setProperties.spec.ts
Labels: eve: release after merged

#3038 fix(createRoot): add missing form state store
  packages/runtime/src/createRoot.ts
Labels: eve: release after merged

#3040 Steve/v3-create-release
  .github/workflows/lerna-version.yml
  bricks/demo-widgets/package.json
  bricks/e2e/package.json
  packages/babel-preset-next/package.json
  packages/brick-container/package.json
  packages/brick-playground/package.json
  packages/browserslist-config-next/package.json
  packages/build-next-bricks/package.json
  packages/build-next-libs/package.json
  packages/cook/package.json
  packages/create-api-sdk/package.json
  packages/element/package.json
  packages/eslint-config-next/package.json
  packages/http/package.json
  packages/i18n/package.json
  packages/inject/package.json
  packages/loader/package.json
  packages/pipes/package.json
  packages/react-element/package.json
  packages/react-runtime/package.json
  packages/runtime/package.json
  packages/serve-helpers/package.json
  packages/supply/package.json
  packages/test-next/package.json
  packages/types/package.json
  packages/utils/package.json
  packages/webpack/package.json
Labels: eve: release after merged

#3042 feat(): support track syntax sugar in v2
  dll/editor-bricks-helper/manifest.snapshot.json
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/src/internal/getTracks.spec.ts
  packages/brick-kit/src/internal/getTracks.ts
  packages/brick-kit/src/internal/setProperties.ts
  packages/brick-kit/src/transformProperties.ts
  packages/brick-utils/src/track.spec.ts
  packages/brick-utils/src/track.ts
  packages/cook/src/preevaluate.spec.ts
  packages/cook/src/preevaluate.ts
  v3/brick-dll-v3/manifest.snapshot.json
Labels: eve: release after merged

#3049 fix(): 增加新插画
  packages/easyops-illustrations/src/images/easyops2/automatic-resource-discovery.png
Labels: eve: release after merged

#3050 Steve/v3-images
  packages/brick-container/serve/getProxy.js
  packages/brick-container/serve/utils/getStandaloneConfig.js
  packages/brick-container/serve/utils/injectIndexHtml.js
  packages/runtime/src/StoryboardFunctionRegistry.spec.ts
  packages/runtime/src/internal/compute/evaluate.spec.ts
  packages/runtime/src/internal/compute/getGeneralGlobals.ts
  packages/runtime/src/internal/compute/images.spec.ts
  packages/runtime/src/internal/compute/images.ts
Labels: eve: release after merged

#3052 fix(): 重新打包
  packages/easyops-illustrations/src/images/easyops2/auto-resource-discovery.png
Labels: eve: release after merged

#3054 Steve/v3-if
  bricks/demo-widgets/CHANGELOG.md
  bricks/demo-widgets/build.config.js
  bricks/demo-widgets/package.json
  bricks/demo-widgets/src/bootstrap.ts
  bricks/demo-widgets/src/index.ts
  bricks/demo-widgets/src/tpl-first-template.ts
  bricks/demo-widgets/src/tpl-second-template.ts
  bricks/demo-widgets/tsconfig.json
  cypress/e2e/control-nodes.spec.js
  mock-micro-apps/auth/storyboard.yaml
  mock-micro-apps/e2e/storyboard.yaml
  mock-micro-apps/home/storyboard.yaml
  mock-micro-apps/test/storyboard.yaml
  packages/runtime/src/Dialog.spec.ts
  packages/runtime/src/Notification.spec.ts
  packages/runtime/src/internal/Renderer.spec.ts
  packages/runtime/src/internal/Renderer.ts
  packages/runtime/src/internal/Runtime.spec.ts
  packages/runtime/src/internal/bindListeners.spec.ts
  packages/runtime/src/internal/compute/evaluate.spec.ts
  packages/runtime/src/internal/data/DataStore.spec.ts
  packages/runtime/src/internal/data/resolveData.spec.ts
  packages/runtime/src/internal/menu/fetchMenuById.spec.ts
  packages/runtime/src/internal/secret_internals.spec.ts
Labels: eve: release after merged

#3055 feat(): support if/esle syntax in v2
  etc/brick-kit.api.md
  etc/brick-types.api.md
  packages/brick-kit/src/checkIf.ts
  packages/brick-kit/src/internal/bindListeners.spec.ts
  packages/brick-kit/src/internal/bindListeners.ts
  packages/brick-types/src/manifest.ts
Labels: eve: release after merged

#3057 Fix/img5.12
  packages/easyops-illustrations/src/images/easyops2/auto-resource-discovery-dark.svg
  packages/easyops-illustrations/src/images/easyops2/auto-resource-discovery.png
  packages/easyops-illustrations/src/images/easyops2/auto-resource-discovery.svg
Labels: eve: release after merged

#3062 chore(): 补充easyhub中应用部署流水线模板的图标 refs EASY_HUB-508
  packages/brick-icons/src/icons/easyhub/easyhub-pipeline-template-add-resource.svg
  packages/brick-icons/src/icons/easyhub/easyhub-pipeline-template-filter.svg
  packages/brick-icons/src/icons/easyhub/easyhub-pipeline-template-resource-detail.svg
  packages/brick-icons/src/icons/easyhub/easyhub-pipeline-template-sotre.svg
Labels: eve: release after merged

#3063 fix(): refactor preview value
  etc/brick-kit.api.md
  packages/brick-kit/src/core/Runtime.ts
  packages/brick-kit/src/core/interfaces.ts
  packages/brick-kit/src/developHelper.ts
Labels: eve: release after merged, [bot]: updated docs etc

#3066 Steve/v3-size-check
  cypress/e2e/control-nodes.spec.js
  cypress/e2e/use-brick.spec.js
  packages/brick-container/serve/env.js
  packages/brick-container/serve/index.js
  packages/brick-container/serve/middlewares/standaloneBootstrapJson.js
  packages/brick-container/serve/utils/getStoryboards.js
  packages/brick-container/serve/utils/sizeCheck.js
  packages/runtime/src/internal/Renderer.spec.ts
  packages/runtime/src/internal/Renderer.ts
  packages/runtime/src/internal/Runtime.spec.ts
  packages/runtime/src/internal/Runtime.ts
Labels: eve: release after merged

#3067 fix(): refine size-check
  packages/brick-container/serve/utils/sizeCheck.js
Labels: eve: release after merged

#3064 feat(): support batchUpdate context
  .size-limit.js
  etc/brick-kit.api.md
  etc/brick-types.api.md
  packages/brick-kit/src/core/StoryboardContext.spec.ts
  packages/brick-kit/src/core/StoryboardContext.ts
  packages/brick-kit/src/internal/bindListeners.spec.ts
  packages/brick-kit/src/internal/bindListeners.ts
  packages/brick-types/src/manifest.ts
  packages/brick-types/src/runtime.ts
Labels: eve: release after merged

#3071 feat(): separate preview and playground
  packages/brick-playground/build.config.js
  packages/brick-playground/package.json
  packages/brick-playground/serve/getExamples.js
  packages/brick-playground/serve/index.js
  packages/brick-playground/src/declarations.d.ts
  packages/brick-playground/src/index.ejs
  packages/brick-playground/src/index.ts
  packages/preview/build.config.js
  packages/preview/package.json
  packages/preview/src/bootstrap.ts
  packages/preview/src/index.css
  packages/preview/src/index.ejs
  packages/preview/src/index.ts
  packages/preview/tsconfig.json
  packages/preview/types.d.ts
  yarn.lock
Labels: eve: release after merged

#3072 feat(): function support RegExp
  packages/cook/src/cook.spec.ts
  packages/cook/src/sanitize.ts
  packages/supply/src/index.ts
Labels: eve: release after merged

#3074 Steve/v3-monaco
  packages/brick-playground/build.config.js
  packages/brick-playground/package.json
  packages/brick-playground/src/index.ts
  packages/monaco-contributions/javascript.d.ts
  packages/monaco-contributions/javascript.js
  packages/monaco-contributions/package.json
  packages/monaco-contributions/typescript.d.ts
  packages/monaco-contributions/typescript.js
  packages/monaco-contributions/yaml.d.ts
  packages/monaco-contributions/yaml.js
Labels: eve: release after merged

#3080 Sailorshe/master/storyboard support parse condtional syntax
  packages/storyboard/src/interfaces.ts
  packages/storyboard/src/parseStoryboard.ts
Labels: eve: release after merged

#3087 Williamcai/custom antd styles button add danger styles
  packages/custom-antd-styles/src/button.less
Labels: eve: release after merged

#3093 fix(): fix track all reg
  packages/cook/src/preevaluate.spec.ts
  packages/cook/src/preevaluate.ts
Labels: eve: release after merged

#3095 feat(): support auth methods
  packages/build-next-bricks/src/build.js
  packages/easyops-runtime/src/auth.spec.ts
  packages/easyops-runtime/src/auth.ts
  packages/easyops-runtime/src/index.ts
Labels: eve: release after merged

#3096 feat(): move menu process from runtime to easyops-runtime
  api-extractor.json
  etc/runtime.api.md
  packages/brick-container/src/bootstrap.ts
  packages/easyops-runtime/package.json
  packages/easyops-runtime/src/auth.ts
  packages/easyops-runtime/src/checkPermissions.spec.ts
  packages/easyops-runtime/src/checkPermissions.ts
  packages/easyops-runtime/src/index.ts
  packages/easyops-runtime/src/menu/computeMenuData.ts
  packages/easyops-runtime/src/menu/constants.ts
  packages/easyops-runtime/src/menu/fetchMenuById.spec.ts
  packages/easyops-runtime/src/menu/fetchMenuById.ts
  packages/easyops-runtime/src/menu/fetchMenuTitle.ts
  packages/easyops-runtime/src/menu/getMenusOfStandaloneApp.ts
  packages/easyops-runtime/src/menu/index.ts
  packages/easyops-runtime/src/menu/interfaces.ts
  packages/easyops-runtime/src/menu/loadDynamicMenuItems.ts
  packages/easyops-runtime/src/menu/mergeMenu.ts
  packages/easyops-runtime/src/menu/reorderMenuItems.ts
  packages/runtime/package.json
  packages/runtime/src/StoryboardFunctionRegistry.spec.ts
  packages/runtime/src/auth.spec.ts
  packages/runtime/src/auth.ts
  packages/runtime/src/index.ts
  packages/runtime/src/internal/Renderer.spec.ts
  packages/runtime/src/internal/Renderer.ts
  packages/runtime/src/internal/Router.ts
  packages/runtime/src/internal/Runtime.ts
  packages/runtime/src/internal/compute/evaluate.spec.ts
  packages/runtime/src/internal/compute/evaluate.ts
  packages/runtime/src/internal/compute/getGeneralGlobals.ts
  packages/runtime/src/internal/matchRoutes.ts
  packages/runtime/src/internal/secret_internals.ts
  packages/runtime/src/internal/test_only.ts
Labels: eve: release after merged

#3100 fix(serve): support --local-bricks
  packages/brick-container/scripts/start.js
  packages/brick-container/serve/env.js
  packages/brick-container/serve/getProxy.js
  packages/brick-container/serve/index.js
  packages/brick-container/serve/middlewares/bootstrapJson.js
  packages/brick-container/serve/middlewares/standaloneBootstrapJson.js
  packages/serve-helpers/index.d.ts
  packages/serve-helpers/src/getBrickPackages.js
Labels: eve: release after merged

#3102 Next
  .lintstagedrc
  docker-compose.yml
  package.json
  packages/babel-preset-next/package.json
  packages/brick-container/package.json
  packages/brick-playground/package.json
  packages/build-next-bricks/package.json
  packages/build-next-libs/package.json
  packages/cook/package.json
  packages/create-api-sdk/package.json
  packages/eslint-config-next/package.json
  packages/i18n/package.json
  packages/runtime/package.json
  packages/test-next/package.json
  yarn.lock
Labels: eve: release after merged

#3108 fix(): fix monaco version not matching
  packages/monaco-contributions/package.json
  yarn.lock
Labels: eve: release after merged

#3109 feat(): menu支持大于两层
  etc/brick-types.api.md
  packages/brick-kit/package.json
  packages/brick-kit/src/internal/menu.spec.ts
  packages/brick-kit/src/internal/menu.ts
  packages/brick-types/src/menu.ts
  yarn.lock
Labels: eve: release after merged

#3115 Steve/renovate-v2
  packages/dev-dependencies/extract.js
  packages/dev-dependencies/patch.js
  packages/dev-dependencies/patches/index.js
  packages/dev-dependencies/patches/updateRenovateForV2.js
  packages/dev-dependencies/patches/updateRenovateForV2.spec.js
Labels: eve: release after merged

#3119 feat(): menu支持大于两层(standalone)
  etc/brick-types.api.md
  packages/brick-kit/package.json
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/internal/menu.spec.ts
  packages/brick-kit/src/internal/menu.ts
  packages/brick-types/src/menu.ts
  packages/brick-utils/src/builder/normalizeMenu.ts
  yarn.lock
Labels: eve: release after merged, [bot]: updating docs etc

#3120 feat(): support extended html syntax: allow dots in tag name
  packages/brick-playground/build.config.js
  packages/brick-playground/src/index.ts
  packages/monaco-contributions/html.d.ts
  packages/monaco-contributions/html.js
  packages/monaco-contributions/package.json
Labels: eve: release after merged

#3122 fix(): normalizeMenu兼容新接口
  .size-limit.js
  packages/brick-utils/src/builder/normalizeMenu.spec.ts
  packages/brick-utils/src/builder/normalizeMenu.ts
Labels: eve: release after merged
