Repository easyops-cn/next-core, pull requests merged in 2023-12, with the labels that each got.

#3679 feat(): support real time data inspect
  .github/workflows/ci.yml
  etc/runtime.api.md
  packages/runtime/src/internal/CustomTemplates/expandCustomTemplate.ts
  packages/runtime/src/internal/FormRenderer/expandFormRenderer.ts
  packages/runtime/src/internal/data/DataStore.spec.ts
  packages/runtime/src/internal/data/DataStore.ts
  packages/runtime/src/internal/data/realTimeDataInspect.spec.ts
  packages/runtime/src/internal/data/realTimeDataInspect.ts
  packages/runtime/src/internal/secret_internals.ts
Labels: eve: release after merged

#3686 feat(): build bricks with insider tag
  packages/brick-manifest/index.d.ts
  packages/build-next-bricks/src/makeBrickManifest.js
Labels: eve: release after merged

#3687 chore(): add icons
  packages/brick-icons/src/icons/app/topology-center.svg
  packages/brick-icons/src/icons/second-menu/layout-second-menu.svg
  packages/brick-icons/src/icons/second-menu/release-second-menu.svg
  packages/brick-icons/src/icons/second-menu/topology-center-second-menu.svg
  packages/brick-icons/src/icons/second-menu/view-arrangement-second-menu.svg
  packages/brick-icons/src/icons/second-menu/view-settings-second-menu.svg
  packages/brick-icons/src/icons/third-menu/cmdb-relation-query-third-menu.svg
  packages/brick-icons/src/icons/third-menu/layout-third-menu.svg
  packages/brick-icons/src/icons/third-menu/release-third-menu.svg
  packages/brick-icons/src/icons/third-menu/topology-center-third-menu.svg
  packages/brick-icons/src/icons/third-menu/view-arrangement-third-menu.svg
Labels: eve: release after merged

#3696 Steve/v3-no-remote
  packages/brick-container/serve/middlewares/getMiddlewares.js
  packages/webpack/src/RuntimePlugin.js
Labels: eve: release after merged

#3697 Icons/garen
  packages/brick-icons/src/icons/app/incident-management.svg
  packages/brick-icons/src/icons/common/analysis.svg
  packages/brick-icons/src/icons/common/association.svg
  packages/brick-icons/src/icons/common/edit-square.svg
  packages/brick-icons/src/icons/common/emergency-plan.svg
  packages/brick-icons/src/icons/common/end.svg
  packages/brick-icons/src/icons/common/play-circle.svg
  packages/brick-icons/src/icons/common/snippets.svg
  packages/brick-icons/src/icons/common/upgradation.svg
  packages/brick-icons/src/icons/second-menu/fault-pool-second-menu.svg
  packages/brick-icons/src/icons/second-menu/incident-management-second-menu.svg
  packages/brick-icons/src/icons/third-menu/fault-pool-third-menu.svg
  packages/brick-icons/src/icons/third-menu/incident-management-third-menu.svg
Labels: eve: release after merged

#3704 chore(): update next-core/theme
  packages/brick-container/package.json
  yarn.lock
Labels: eve: release after merged

#3707 feat(): support build brick with stories
  packages/build-next-bricks/bin/build-next-bricks.js
  packages/build-next-bricks/src/buildStories.js
Labels: eve: release after merged

#3714 fix(): fix permission check in dynamic menu items
  packages/easyops-runtime/src/menu/fetchMenuById.spec.ts
  packages/easyops-runtime/src/menu/loadDynamicMenuItems.ts
Labels: eve: release after merged

#3716 chore(): 增加事件总线icon refs ALERT_EVENT-974
  packages/brick-icons/src/icons/app/event-bridge.svg
  packages/brick-icons/src/icons/second-menu/event-bridge-second-menu.svg
  packages/brick-icons/src/icons/second-menu/target-second-menu.svg
  packages/brick-icons/src/icons/third-menu/event-bridge-third-menu.svg
  packages/brick-icons/src/icons/third-menu/target-third-menu.svg
Labels: eve: release after merged

#3717 chore():add icons
  packages/brick-icons/src/icons/monitor/root-cause-alert.svg
  packages/brick-icons/src/icons/monitor/root-cause-deployment.svg
  packages/brick-icons/src/icons/monitor/root-cause-high-load.svg
  packages/brick-icons/src/icons/monitor/root-cause-oom.svg
Labels: eve: release after merged

#3723 chore(): replace icons
  packages/brick-icons/src/icons/colored-common/root-cause-alert.svg
  packages/brick-icons/src/icons/colored-common/root-cause-deployment.svg
  packages/brick-icons/src/icons/colored-common/root-cause-high-load.svg
  packages/brick-icons/src/icons/colored-common/root-cause-oom.svg
  packages/brick-icons/src/icons/monitor/root-cause-high-load.svg
Labels: eve: release after merged

#3725 chore(): add sys-setting
  packages/public-scoped-sdk/index.js
Labels: eve: release after merged

#3726 chore(): sdk update
  packages/public-scoped-sdk/index.js
Labels: eve: release after merged

#3732 feat(): support real time query
  etc/brick-kit.api.md
  packages/brick-kit/src/getRealValue.spec.ts
  packages/brick-kit/src/getRealValue.ts
  packages/brick-kit/src/internal/evaluate.spec.ts
  packages/brick-kit/src/internal/evaluate.ts
Labels: eve: release after merged, [bot]: updated docs etc

#3733 fix(): Provider::saveAs requires the first argument to be the filename
  packages/brick-kit/src/core/FlowApi.ts
Labels: eve: release after merged

#3735 chore(): 上传图标
  packages/brick-icons/src/icons/second-menu/permission-inheritance-second-menu.svg
Labels: eve: release after merged

#3737 fix(): optional use real time query in placeholders
  packages/brick-kit/src/getRealValue.spec.ts
  packages/brick-kit/src/getRealValue.ts
  packages/brick-kit/src/internal/evaluate.spec.ts
  packages/brick-kit/src/internal/evaluate.ts
Labels: eve: release after merged, [bot]: updating docs etc

#3740 chore(): 上传图标
  packages/brick-icons/src/icons/second-menu/permission-inheritance-second-menu.svg
Labels: eve: release after merged

#3741 feat(): update reportInstalledBrickNextPackage.py
  packages/brick-container/tools/report_installed_brick_next_package.py
Labels: eve: release after merged

#3738 feat(): update report_install_brick_next_package
  packages/brick-container/tools/report_installed_brick_next_package.py
Labels: eve: release after merged

#3743 feat(): track conditional resolve
  packages/runtime/src/internal/data/DataStore.spec.ts
  packages/runtime/src/internal/data/DataStore.ts
Labels: eve: release after merged

#3744 feat(): track conditional resolve
  etc/brick-types.api.md
  packages/brick-kit/src/core/StoryboardContext.spec.ts
  packages/brick-kit/src/core/StoryboardContext.ts
  packages/brick-kit/src/internal/bindListeners.spec.ts
  packages/brick-types/src/runtime.ts
Labels: eve: release after merged

#3751 chore(): add icons
  packages/brick-icons/src/icons/app/capacity-management-app.svg
  packages/brick-icons/src/icons/second-menu/capacity-management-second-menu.svg
  packages/brick-icons/src/icons/second-menu/high-load-second-menu.svg
  packages/brick-icons/src/icons/second-menu/low-load-second-menu.svg
  packages/brick-icons/src/icons/third-menu/capacity-management-third-menu.svg
  packages/brick-icons/src/icons/third-menu/high-load-third-menu.svg
  packages/brick-icons/src/icons/third-menu/low-load-third-menu.svg
Labels: eve: release after merged

#3752 chore(): update next-core/theme
  packages/theme/src/dark.css
  packages/theme/src/default.css
Labels: eve: release after merged

#3773 fix(): fallback i18next to v22, which supports old browsers (es5)
  packages/i18n/package.json
  packages/i18n/src/index.ts
  yarn.lock
Labels: eve: release after merged

#3782 fix(): fix v3 widget upload error
  packages/brick-container/tools/report_installed_brick_next_package.py
Labels: eve: release after merged

#3783 fix(): fix v3 widget upload error
  packages/brick-container/tools/report_installed_brick_next_package.py
Labels: eve: release after merged

#3784 chore(): update tag css variable
  packages/theme/src/default.css
  packages/theme/src/variables.css
Labels: eve: release after merged

#3789 chore(): report ingore package without stories.json
  packages/brick-container/tools/report_installed_brick_next_package.py
Labels: eve: release after merged

#3790 chore(): report ingore package without stories.json
  packages/brick-container/tools/report_installed_brick_next_package.py
Labels: eve: release after merged

#3785 fix(): use correct runtime context for useBrick within createRoot
  etc/runtime.api.md
  packages/element/src/NextElement.spec.ts
  packages/element/src/createDecorators.ts
  packages/element/src/interfaces.ts
  packages/react-runtime/src/ReactUseBrick.spec.tsx
  packages/react-runtime/src/ReactUseBrick.tsx
  packages/runtime/src/createRoot.ts
  packages/runtime/src/internal/Runtime.ts
  packages/runtime/src/internal/secret_internals.spec.ts
  packages/runtime/src/internal/secret_internals.ts
  packages/runtime/src/internal/setupRootRuntimeContext.spec.ts
  packages/runtime/src/internal/setupRootRuntimeContext.ts
Labels: eve: release after merged, [bot]: updating docs etc

#3796 feat(): before build bricks, remove their peerDependencies
  packages/build-next-bricks/bin/post-build-next-bricks.js
  packages/build-next-bricks/bin/pre-build-next-bricks.js
Labels: eve: release after merged
