Repository easyops-cn/next-core, pull requests merged in 2023-01, with the labels that each got.

#2567 chore(): 添加模型icon
  .size-limit.js
  packages/brick-icons/src/icons/model/amqp.svg
  packages/brick-icons/src/icons/model/clickhouse.svg
  packages/brick-icons/src/icons/model/etcd.svg
  packages/brick-icons/src/icons/model/http.svg
  packages/brick-icons/src/icons/model/mssql.svg
Labels: eve: release after merged

#2568 fix(): fix standalone bootstrap failed to inject menus
  packages/brick-kit/src/core/standaloneBootstrap.ts
Labels: eve: release after merged

#2570 feat(): update pageNotFound page style
  cypress/e2e/404.spec.js
  package.json
  packages/brick-container/serve/serve.js
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/Router.spec.ts
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/i18n/constants.ts
  packages/brick-kit/src/i18n/locales/en.ts
  packages/brick-kit/src/i18n/locales/zh.ts
  yarn.lock
Labels: eve: release after merged

#2577 fix(): 增加AuthInfo接口字段 refs USER-4
  etc/brick-types.api.md
  packages/brick-types/src/manifest.ts
Labels: eve: release after merged

#2580 fix(): 修复formRender中properties的表达式无法解析
  packages/brick-kit/src/core/LocationContext.ts
Labels: eve: release after merged

#2581 fix(table-less): 复原filter图标位置样式
  packages/custom-antd-styles/src/table.less
Labels: eve: release after merged

#2582 feat(): support useBrick with tpl resolve state
  packages/brick-kit/src/BrickAsComponent.spec.tsx
  packages/brick-kit/src/BrickAsComponent.tsx
  packages/brick-kit/src/core/CustomForms/ExpandCustomForm.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/LocationContext.ts
  packages/brick-kit/src/core/Runtime.ts
Labels: eve: release after merged

#2585 fix(): fix menu with PERMISSIONS.check
  packages/brick-kit/src/internal/menu.spec.ts
  packages/brick-kit/src/internal/menu.ts
Labels: eve: release after merged

#2588 fix(): favicon repeat render
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/core/Runtime.ts
Labels: eve: release after merged

#2589 fix(): 更改button样式 更改info和danger的颜色 size为sm的尺寸
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
  packages/custom-antd-styles/src/button.less
Labels: eve: release after merged

#2590 fix(): 增加userShowValue字段 refs USER-4
  packages/brick-kit/src/auth.ts
Labels: eve: release after merged

#2591 fix(): 更改构件圆角
  packages/brick-container/src/styles/theme/default.css
  packages/brick-container/src/styles/variables.css
  packages/custom-antd-styles/src/button.less
  packages/custom-antd-styles/src/card.less
  packages/custom-antd-styles/src/date-picker.less
  packages/custom-antd-styles/src/input.less
Labels: eve: release after merged

#2592 fix(): concurrently load bricks and business apis
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/LocationContext.spec.ts
  packages/brick-kit/src/core/LocationContext.ts
  packages/brick-kit/src/core/Router.spec.ts
  packages/brick-kit/src/core/Router.ts
Labels: eve: release after merged

#2597 fix(): fix concurrently load bricks and business apis
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-utils/src/getDllAndDepsOfStoryboard.spec.ts
  packages/brick-utils/src/getDllAndDepsOfStoryboard.ts
Labels: eve: release after merged

#2602 feat(): brickAsComponent支持form_state表达式解析，refs: ITSERVICE_NEXT-5450
  etc/brick-kit.api.md
  packages/brick-kit/src/BrickAsComponent.spec.tsx
  packages/brick-kit/src/BrickAsComponent.tsx
  packages/brick-kit/src/core/CustomForms/constants.ts
  packages/brick-kit/src/transformProperties.ts
Labels: eve: release after merged, [bot]: updated docs etc

#2603 fix(): 去掉table.less中的filter图标覆盖
  packages/custom-antd-styles/src/table.less
Labels: eve: release after merged

#2606 fix(): make context requests be parallel for nested routes
  .size-limit.js
  dll/editor-bricks-helper/manifest.snapshot.json
  etc/brick-kit.api.md
  packages/brick-dll/manifest.snapshot.json
  packages/brick-kit/src/core/CustomForms/CustomFormContext.ts
  packages/brick-kit/src/core/CustomForms/ExpandCustomForm.ts
  packages/brick-kit/src/core/CustomTemplates/expandCustomTemplate.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/LocationContext.spec.ts
  packages/brick-kit/src/core/LocationContext.ts
  packages/brick-kit/src/core/Resolver.spec.ts
  packages/brick-kit/src/core/Resolver.ts
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/core/StoryboardContext.spec.ts
  packages/brick-kit/src/core/StoryboardContext.ts
  packages/brick-kit/src/core/__mocks__/LocationContext.ts
  packages/brick-kit/src/internal/getSubStoryboardByRoute.spec.ts
  packages/brick-kit/src/internal/getSubStoryboardByRoute.ts
  packages/brick-kit/src/internal/menu.spec.ts
  packages/brick-kit/src/internal/menu.ts
  packages/brick-utils/src/resolveContextConcurrently.spec.ts
  packages/brick-utils/src/resolveContextConcurrently.ts
  packages/brick-utils/src/track.ts
Labels: eve: release after merged

#2607 feat(): enable --runInBand for test:ci
  packages/dev-dependencies/patch.js
Labels: eve: release after merged

#2609 Steve/fix parallel ctx
  packages/brick-kit/src/core/StoryboardContext.spec.ts
  packages/brick-kit/src/core/StoryboardContext.ts
  packages/brick-kit/src/internal/menu.ts
  packages/brick-utils/src/resolveContextConcurrently.spec.ts
  packages/brick-utils/src/resolveContextConcurrently.ts
Labels: eve: release after merged

#2610 fix(): fix brick preview with provider
  packages/brick-kit/src/core/Runtime.ts
Labels: eve: release after merged

#2611 fix(test:ci): disable runInBand
  packages/dev-dependencies/patch.js
Labels: eve: release after merged

#2600 feat(): support brick preview in iframe
  .size-limit.js
  etc/brick-kit.api.md
  packages/brick-container/src/preview.ejs
  packages/brick-container/src/preview.ts
  packages/brick-container/src/styles/preview.css
  packages/brick-container/webpack/common.js
  packages/brick-kit/src/core/Router.ts
  packages/brick-kit/src/core/Runtime.ts
  packages/brick-kit/src/developHelper.ts
Labels: [bot]: updating dll manifest

#2615 fix(): 改变组件间距以及input和button的圆角
  packages/brick-container/src/styles/variables.css
  packages/custom-antd-styles/src/button.less
  packages/custom-antd-styles/src/card.less
  packages/custom-antd-styles/src/input.less
Labels: eve: release after merged

#2617 fix(): fix loading widgets
  packages/brick-kit/src/core/Kernel.spec.ts
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-utils/src/getDllAndDepsOfStoryboard.spec.ts
  packages/brick-utils/src/getDllAndDepsOfStoryboard.ts
Labels: eve: release after merged

#2621 fix(): 修复overrideApp没有合并defaultConfig和userConfig的问题
  packages/brick-kit/src/internal/menu.spec.ts
  packages/brick-kit/src/internal/menu.ts
Labels: eve: release after merged

#2624 fix(): 修改卡片间距
  packages/brick-container/src/styles/variables.css
  packages/custom-antd-styles/src/card.less
Labels: eve: release after merged

#2626 fix(): changeBorderRadiusOfInputGroup
  packages/custom-antd-styles/src/input.less
Labels: eve: release after merged

#2627 fix(): fixBorderRadiusOfInputGroupfist-child
  packages/custom-antd-styles/src/input.less
Labels: eve: release after merged
