Repository easyops-cn/next-core, pull requests merged in 2023-04, with the labels that each got.

#2909 feat(): v3 strict mode
  packages/brick-playground/src/preview/bootstrap.ts
  packages/runtime/src/CustomTemplates.spec.ts
  packages/runtime/src/CustomTemplates.ts
  packages/runtime/src/internal/Renderer.spec.ts
  packages/runtime/src/internal/Renderer.ts
  packages/runtime/src/internal/RendererContext.ts
  packages/runtime/src/internal/compute/evaluate.spec.ts
  packages/runtime/src/internal/compute/evaluate.ts
  packages/runtime/src/internal/data/FlowApi.spec.ts
  packages/runtime/src/internal/data/FlowApi.ts
  packages/runtime/src/internal/data/resolveData.spec.ts
  packages/runtime/src/internal/data/resolveData.ts
  packages/runtime/src/internal/secret_internals.spec.ts
  packages/runtime/src/internal/secret_internals.ts
  packages/runtime/src/isStrictMode.spec.ts
  packages/runtime/src/isStrictMode.ts
  packages/utils/src/storyboard/expressions/collectMemberUsage.ts
  packages/utils/src/storyboard/functions/collectMemberUsageInFunction.spec.ts
  packages/utils/src/storyboard/functions/collectMemberUsageInFunction.ts
Labels: eve: release after merged

#2918 Steve/v3-nested-use-brick-and-tpl
  bricks/e2e/src/bootstrap.ts
  bricks/e2e/src/data-providers/return-by-timeout.ts
  cypress/e2e/use-brick.spec.js
  mock-micro-apps/e2e/storyboard.yaml
  packages/runtime/src/internal/CustomTemplates/expandCustomTemplate.ts
  packages/runtime/src/internal/compute/evaluate.ts
  packages/runtime/src/internal/interfaces.ts
  packages/runtime/src/internal/secret_internals.ts
Labels: eve: release after merged

#2919 feat(): support preview in visual builder
  packages/brick-container/scripts/start.js
  packages/brick-container/src/bootstrap.ts
  packages/runtime/src/index.ts
  packages/runtime/src/internal/Router.ts
  packages/runtime/src/internal/insertPreviewRoutes.spec.ts
  packages/runtime/src/internal/insertPreviewRoutes.ts
  packages/runtime/src/internal/secret_internals.spec.ts
  packages/runtime/src/internal/secret_internals.ts
Labels: eve: release after merged

#2923 fix(): only warn about using native props as tpl props in non-strict mode
  packages/runtime/src/CustomTemplates.spec.ts
  packages/runtime/src/CustomTemplates.ts
Labels: eve: release after merged

#2926 chore(): add api-extractor for runtime
  .github/workflows/update-docs-etc.yml
  .gitignore
  api-extractor.json
  etc/runtime.api.md
  packages/runtime/api-extractor.json
  packages/runtime/package.json
  packages/runtime/src/index.ts
  yarn.lock
Labels: [bot]: updated docs etc

#2929 chore(): add icons
  packages/brick-icons/src/icons/second-menu/alibaba-ecs-second-menu.svg
  packages/brick-icons/src/icons/second-menu/apachel-second-menu.svg
  packages/brick-icons/src/icons/second-menu/area-second-menu.svg
  packages/brick-icons/src/icons/second-menu/availability-zone-second-menu.svg
  packages/brick-icons/src/icons/second-menu/backend-second-menu.svg
  packages/brick-icons/src/icons/second-menu/broadband-line-second-menu.svg
  packages/brick-icons/src/icons/second-menu/cabinet-list-second-menu.svg
  packages/brick-icons/src/icons/second-menu/cabinet-second-menu.svg
  packages/brick-icons/src/icons/second-menu/computer-room-details-second-menu.svg
  packages/brick-icons/src/icons/second-menu/connection-second-menu.svg
  packages/brick-icons/src/icons/second-menu/engine-room-second-menu.svg
  packages/brick-icons/src/icons/second-menu/frontend-second-menu.svg
  packages/brick-icons/src/icons/second-menu/host-second-menu.svg
  packages/brick-icons/src/icons/second-menu/infra-monitor-second-menu.svg
  packages/brick-icons/src/icons/second-menu/ip-second-menu.svg
  packages/brick-icons/src/icons/second-menu/ip-segment-second-menu.svg
  packages/brick-icons/src/icons/second-menu/jboss-second-menu.svg
  packages/brick-icons/src/icons/second-menu/key-second-menu.svg
  packages/brick-icons/src/icons/second-menu/mssql-second-menu.svg
  packages/brick-icons/src/icons/second-menu/queue-second-menu.svg
  packages/brick-icons/src/icons/second-menu/release-ticket-second-menu.svg
  packages/brick-icons/src/icons/second-menu/resource-pool-second-menu.svg
  packages/brick-icons/src/icons/second-menu/supplier-second-menu.svg
  packages/brick-icons/src/icons/second-menu/tencent-cloud-hard-disk-second-menu.svg
  packages/brick-icons/src/icons/second-menu/tencent-cvm-second-menu.svg
  packages/brick-icons/src/icons/second-menu/tidb-second-menui.svg
  packages/brick-icons/src/icons/second-menu/tomcat-second-menu.svg
  packages/brick-icons/src/icons/second-menu/tongweb-second-menu.svg
  packages/brick-icons/src/icons/second-menu/vm-host-machine-second-menu.svg
  packages/brick-icons/src/icons/second-menu/weblogic-second-menu.svg
  packages/brick-icons/src/icons/second-menu/website-second-menu.svg
  packages/brick-icons/src/icons/third-menu/apachel-third-menu.svg
  packages/brick-icons/src/icons/third-menu/area-third-menu.svg
  packages/brick-icons/src/icons/third-menu/availability-zone-third-menu.svg
  packages/brick-icons/src/icons/third-menu/backend-third-menu.svg
  packages/brick-icons/src/icons/third-menu/broadband-line-third-menu.svg
  packages/brick-icons/src/icons/third-menu/cabinet-list-third-menu.svg
  packages/brick-icons/src/icons/third-menu/cabinet-third-menu.svg
  packages/brick-icons/src/icons/third-menu/computer-room-details-third-menu.svg
  packages/brick-icons/src/icons/third-menu/connection-third-menu.svg
  packages/brick-icons/src/icons/third-menu/engine-room-third-menu.svg
  packages/brick-icons/src/icons/third-menu/frontend-third-menu.svg
  packages/brick-icons/src/icons/third-menu/infra-monitor-third-menu.svg
  packages/brick-icons/src/icons/third-menu/ip-segment-third-menu.svg
  packages/brick-icons/src/icons/third-menu/ip-third-menu.svg
  packages/brick-icons/src/icons/third-menu/jboss-third-menu.svg
  packages/brick-icons/src/icons/third-menu/queue-third-menu.svg
  packages/brick-icons/src/icons/third-menu/supplier-third-menu.svg
  packages/brick-icons/src/icons/third-menu/tencent-cloud-hard-disk-third-menu.svg
  packages/brick-icons/src/icons/third-menu/tidb-third-menu.svg
  packages/brick-icons/src/icons/third-menu/tomcat-third-menu.svg
  packages/brick-icons/src/icons/third-menu/tongweb-third-menu.svg
  packages/brick-icons/src/icons/third-menu/vm-host-machine-third-menu.svg
  packages/brick-icons/src/icons/third-menu/weblogic-third-menu.svg
  packages/brick-icons/src/icons/third-menu/website-third-menu.svg
Labels: eve: release after merged

#2935 fix(): fix feature flags in playground
  packages/runtime/src/internal/Runtime.spec.ts
  packages/runtime/src/internal/Runtime.ts
Labels: eve: release after merged

#2936 fix(): 上传新的二级/三级菜单图标
  packages/brick-icons/src/icons/second-menu/persistent-volume-statement-second-menu.svg
  packages/brick-icons/src/icons/second-menu/serve-second-menu.svg
  packages/brick-icons/src/icons/third-menu/persistent-volume-statement-third-menu.svg
  packages/brick-icons/src/icons/third-menu/serve-third-menu.svg
Labels: eve: release after merged

#2937 chore(): add icons
  packages/brick-icons/src/icons/colored-common/baoan.svg
  packages/brick-icons/src/icons/colored-common/be-in-common-use.svg
  packages/brick-icons/src/icons/colored-common/commercial-centre.svg
  packages/brick-icons/src/icons/colored-common/dapeng.svg
  packages/brick-icons/src/icons/colored-common/exhibition-hall.svg
  packages/brick-icons/src/icons/colored-common/flats.svg
  packages/brick-icons/src/icons/colored-common/futian.svg
  packages/brick-icons/src/icons/colored-common/guangming.svg
  packages/brick-icons/src/icons/colored-common/longgang.svg
  packages/brick-icons/src/icons/colored-common/longhua.svg
  packages/brick-icons/src/icons/colored-common/luohu.svg
  packages/brick-icons/src/icons/colored-common/nanshan.svg
  packages/brick-icons/src/icons/colored-common/office-building.svg
  packages/brick-icons/src/icons/colored-common/performing-arts-hall.svg
  packages/brick-icons/src/icons/colored-common/pingshan.svg
  packages/brick-icons/src/icons/colored-common/wineshop.svg
  packages/brick-icons/src/icons/colored-common/yantian.svg
Labels: eve: release after merged

#2943 Steve/add-data-source
  packages/brick-container/serve/getProxies.js
  packages/brick-utils/src/builder/normalizeBuilderNode.ts
Labels: eve: release after merged

#2942 Zekun/icons
  packages/brick-icons/src/icons/second-menu/amq-second-menu.svg
  packages/brick-icons/src/icons/second-menu/continuous-integration-second-menu.svg
  packages/brick-icons/src/icons/second-menu/haproxy-second-menu.svg
  packages/brick-icons/src/icons/second-menu/postgresql-second-menu.svg
Labels: eve: release after merged

#2947 fix(icons): 替换icon
  packages/brick-icons/src/icons/second-menu/haproxy-second-menu.svg
Labels: eve: release after merged

#2949 chore(): add icons
  packages/brick-icons/src/icons/colored-common/business.svg
  packages/brick-icons/src/icons/colored-common/inventory.svg
  packages/brick-icons/src/icons/colored-common/item.svg
  packages/brick-icons/src/icons/colored-common/partake.svg
  packages/brick-icons/src/icons/colored-common/present-situation.svg
  packages/brick-icons/src/icons/colored-common/quota.svg
  packages/brick-icons/src/icons/colored-common/target.svg
Labels: eve: release after merged

#2954 chore(): add icons
  packages/brick-icons/src/icons/second-menu/alisql-second-menu.svg
  packages/brick-icons/src/icons/second-menu/gaussdb-for-opengauss-second-menu.svg
  packages/brick-icons/src/icons/second-menu/oceanbase-second-menu.svg
  packages/brick-icons/src/icons/second-menu/polardb-oracle-second-menu.svg
  packages/brick-icons/src/icons/second-menu/sybase-second-menu.svg
  packages/brick-icons/src/icons/second-menu/tdsql-for-mysql-second-menu.svg
Labels: eve: release after merged

#2952 Williamcai/update UI 8.2 compact layout content style
  packages/brick-container/src/styles/variables.css
Labels: eve: release after merged

#2951 Steve/v3 third party bricks
  etc/runtime.api.md
  packages/brick-playground/src/preview/bootstrap.ts
  packages/build-next-bricks/index.d.ts
  packages/build-next-bricks/src/EmitBricksJsonPlugin.js
  packages/build-next-bricks/src/build.js
  packages/build-next-bricks/src/scanBricks.js
  packages/loader/src/stableLoadBricks.spec.ts
  packages/loader/src/stableLoadBricks.ts
  packages/runtime/src/Dialog.spec.ts
  packages/runtime/src/Dialog.ts
  packages/runtime/src/Notification.spec.ts
  packages/runtime/src/Notification.ts
  packages/runtime/src/handleHttpError.spec.ts
  packages/runtime/src/handleHttpError.ts
  packages/runtime/src/index.ts
  packages/runtime/src/internal/CustomTemplates/utils.ts
  packages/runtime/src/internal/Renderer.ts
  packages/runtime/src/internal/Runtime.spec.ts
  packages/runtime/src/internal/Runtime.ts
  packages/runtime/src/internal/bindListeners.ts
  packages/runtime/src/internal/i18n.ts
  packages/runtime/src/internal/secret_internals.ts
  packages/types/src/manifest.ts
Labels: eve: release after merged, [bot]: updated docs etc

#2955 fix(): fix loading processors in widgets
  packages/brick-kit/src/core/Kernel.ts
  packages/brick-kit/src/core/LocationContext.spec.ts
  packages/brick-kit/src/core/LocationContext.ts
Labels: eve: release after merged

#2956 fix(): treat css imports other than css modules as text file
  packages/test-next/src/createJestConfig.js
Labels: eve: release after merged

#2957 fix(): NEXT_BUILDER-2934 二级菜单分类颜色需替换
  packages/brick-container/src/styles/theme/dark.css
  packages/brick-container/src/styles/theme/default.css
Labels: eve: release after merged

#2959 fix(): refine dialog service
  etc/runtime.api.md
  packages/runtime/src/Dialog.spec.ts
  packages/runtime/src/Dialog.ts
  packages/runtime/src/handleHttpError.spec.ts
  packages/runtime/src/handleHttpError.ts
  packages/runtime/src/internal/i18n.ts
Labels: eve: release after merged, [bot]: updated docs etc

#2960 fix(): fix isOutsideApp
  packages/runtime/src/internal/Runtime.ts
  packages/runtime/src/internal/matchStoryboard.ts
Labels: eve: release after merged

#2963 feat(wrapLocalBrick): allow pass brick name
  packages/react-element/src/wrapBrick.spec.tsx
  packages/react-element/src/wrapBrick.tsx
Labels: eve: release after merged

#2962 fix(): fix isOutsideApp
  packages/brick-kit/src/core/matchStoryboard.ts
Labels: eve: release after merged

#2964 feat(): createRoot
  .eslintrc
  etc/runtime.api.md
  packages/brick-playground/src/index.ts
  packages/brick-playground/src/preview/bootstrap.ts
  packages/loader/package.json
  packages/loader/src/standalone.spec.ts
  packages/loader/src/standalone.ts
  packages/loader/tsconfig.json
  packages/runtime/src/Dialog.spec.ts
  packages/runtime/src/Dialog.ts
  packages/runtime/src/Notification.spec.ts
  packages/runtime/src/Notification.ts
  packages/runtime/src/createRoot.spec.ts
  packages/runtime/src/createRoot.ts
  packages/runtime/src/index.ts
  packages/runtime/src/internal/Renderer.spec.ts
  packages/runtime/src/internal/Renderer.ts
  packages/runtime/src/internal/RendererContext.ts
  packages/runtime/src/internal/Router.ts
  packages/runtime/src/internal/Runtime.ts
  packages/runtime/src/internal/bootstrapData.ts
  packages/runtime/src/internal/menu/fetchMenuById.spec.ts
  packages/runtime/src/internal/secret_internals.spec.ts
  packages/runtime/src/internal/secret_internals.ts
  packages/serve-helpers/index.d.ts
  packages/serve-helpers/src/getBrickPackages.js
  packages/webpack/index.d.ts
  packages/webpack/index.js
  packages/webpack/jsconfig.json
  packages/webpack/package.json
  packages/webpack/src/BricksPlugin.js
  packages/webpack/src/RuntimePlugin.js
Labels: eve: release after merged, [bot]: updated docs etc

#2975 Steve/v3-build
  packages/build-next-bricks/src/build.js
  packages/webpack/index.d.ts
  packages/webpack/src/RuntimePlugin.js
Labels: eve: release after merged

#2981 Steve/v3 refine create root
  etc/runtime.api.md
  packages/brick-playground/package.json
  packages/brick-playground/src/declarations.d.ts
  packages/brick-playground/src/index.ts
  packages/brick-playground/src/preview/bootstrap.ts
  packages/brick-playground/src/preview/preview.css
  packages/brick-playground/src/preview/preview.ejs
  packages/runtime/src/createRoot.spec.ts
  packages/runtime/src/createRoot.ts
  packages/runtime/src/internal/registerAppI18n.ts
  packages/runtime/src/internal/secret_internals.ts
  packages/webpack/index.d.ts
  packages/webpack/src/RuntimePlugin.js
Labels: eve: release after merged

#2982 fix(): reset preview body height to initial
  packages/brick-playground/src/preview/bootstrap.ts
  packages/brick-playground/src/preview/preview.css
  packages/brick-playground/src/preview/preview.ejs
Labels: eve: release after merged

#2985 chore(): add icons
  packages/brick-icons/src/icons/second-menu/carbon-second-menu.svg
  packages/brick-icons/src/icons/second-menu/enterprise-second-menu.svg
  packages/brick-icons/src/icons/second-menu/fill-in-second-menu.svg
  packages/brick-icons/src/icons/third-menu/carbon-third-menu.svg
  packages/brick-icons/src/icons/third-menu/enterprise-third-menu.svg
  packages/brick-icons/src/icons/third-menu/fill-in-third-menu.svg
Labels: eve: release after merged

#2986 fix(): fix multi-instance of useBrick state conflict
  packages/brick-kit/src/core/CustomTemplates/__snapshots__/expandCustomTemplate.spec.ts.snap
  packages/brick-kit/src/core/CustomTemplates/expandCustomTemplate.ts
  packages/brick-kit/src/core/CustomTemplates/setupUseBrickInTemplate.spec.ts
  packages/brick-kit/src/core/CustomTemplates/setupUseBrickInTemplate.ts
  packages/brick-kit/src/internal/setProperties.spec.ts
  packages/brick-kit/src/internal/setProperties.ts
Labels: eve: release after merged

#2987 feat(preview): allow adding style
  packages/brick-playground/src/declarations.d.ts
  packages/brick-playground/src/preview/bootstrap.ts
Labels: eve: release after merged

#2993 Steve/v3-form-renderer
  packages/brick-container/serve/middlewares/getMiddlewares.js
  packages/runtime/src/internal/CustomTemplates/expandCustomTemplate.ts
  packages/runtime/src/internal/CustomTemplates/utils.ts
  packages/runtime/src/internal/FormRenderer/constants.ts
  packages/runtime/src/internal/FormRenderer/expandFormRenderer.ts
  packages/runtime/src/internal/FormRenderer/getDefaultProperties.ts
  packages/runtime/src/internal/FormRenderer/interfaces.ts
  packages/runtime/src/internal/FormRenderer/utils.spec.ts
  packages/runtime/src/internal/FormRenderer/utils.ts
  packages/runtime/src/internal/Renderer.spec.ts
  packages/runtime/src/internal/Renderer.ts
  packages/runtime/src/internal/Router.ts
  packages/runtime/src/internal/bindListeners.spec.ts
  packages/runtime/src/internal/bindListeners.ts
  packages/runtime/src/internal/compute/evaluate.ts
  packages/runtime/src/internal/compute/listenOnTrackingContext.spec.ts
  packages/runtime/src/internal/compute/listenOnTrackingContext.ts
  packages/runtime/src/internal/data/DataStore.ts
  packages/runtime/src/internal/interfaces.ts
  packages/runtime/src/internal/secret_internals.ts
Labels: eve: release after merged

#2992 Sailorshe/master/support menu image
  packages/brick-container/serve/getIndexHtml.js
  packages/brick-container/serve/getProxies.js
  packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.spec.ts
  packages/brick-kit/src/internal/evaluate.spec.ts
  packages/brick-kit/src/internal/getGeneralGlobals.ts
  packages/brick-kit/src/internal/images.spec.ts
  packages/brick-kit/src/internal/images.ts
  packages/brick-kit/src/internal/menu.ts
Labels: eve: release after merged

#2999 chore(icons): add icons
  packages/brick-icons/src/icons/blueprint/resize.svg
  packages/brick-icons/src/icons/blueprint/toggle-blueprint.svg
  packages/brick-icons/src/icons/blueprint/upgrade.svg
Labels: eve: release after merged

#2997 refactor(): move bootstrap fetching outside of runtime
  CONTRIBUTING-V3.md
  etc/runtime.api.md
  packages/brick-container/package.json
  packages/brick-container/src/bootstrap.ts
  packages/brick-container/src/loadBootstrapData.spec.ts
  packages/brick-container/src/loadBootstrapData.ts
  packages/brick-container/src/loadCheckLogin.ts
  packages/brick-playground/src/preview/bootstrap.ts
  packages/runtime/src/Dialog.spec.ts
  packages/runtime/src/Dialog.ts
  packages/runtime/src/Notification.spec.ts
  packages/runtime/src/Notification.ts
  packages/runtime/src/index.ts
  packages/runtime/src/internal/Router.ts
  packages/runtime/src/internal/Runtime.spec.ts
  packages/runtime/src/internal/Runtime.ts
  packages/runtime/src/internal/bootstrapData.ts
  packages/runtime/src/internal/fulfilStoryboard.ts
  packages/runtime/src/internal/menu/fetchMenuById.spec.ts
  packages/runtime/src/internal/secret_internals.spec.ts
  packages/runtime/src/internal/secret_internals.ts
  packages/types/src/manifest.ts
Labels: eve: release after merged

#3000 Steve/v3-inject
  packages/runtime/src/internal/Runtime.spec.ts
  packages/runtime/src/internal/Runtime.ts
  packages/runtime/src/internal/bootstrapData.ts
  packages/runtime/src/internal/injected.ts
  packages/types/src/manifest.ts
  packages/webpack/src/RuntimePlugin.js
Labels: eve: release after merged

#3001 fix(): allow bootstrap with initializing data
  packages/brick-container/src/bootstrap.ts
  packages/runtime/src/internal/Runtime.spec.ts
  packages/runtime/src/internal/Runtime.ts
Labels: eve: release after merged
